export const champs = {
	"champions": [
		{ "name": "Aatrox", "lanes": ["Top"], "lolid": "0266" },
		{ "name": "Ahri", "lanes": ["Mid"], "lolid": "0103" },
		{ "name": "Akali", "lanes": ["Mid", "Top"], "lolid": "0084" },
		{ "name": "Akshan", "lanes": ["Mid", "Top"], "lolid": "0166" },
		{ "name": "Alistar", "lanes": ["Support"], "lolid": "0012" },
		{ "name": "Amumu", "lanes": ["Jungle", "Support"], "lolid": "0032" },
		{ "name": "Anivia", "lanes": ["Mid", "Support"], "lolid": "0034" },
		{ "name": "Annie", "lanes": ["Mid"], "lolid": "0001" },
		{ "name": "Aphelios", "lanes": ["ADC"], "lolid": "0523" },
		{ "name": "Ashe", "lanes": ["ADC", "Support"], "lolid": "0022" },
		{ "name": "Aurelion Sol", "lanes": ["Mid"], "lolid": "0524" },
		{ "name": "Azir", "lanes": ["Mid"], "lolid": "0268" },
		{ "name": "Bard", "lanes": ["Support"], "lolid": "0432" },
		{ "name": "Bel'Veth", "lanes": ["Jungle"], "lolid": "0200" },
		{ "name": "Blitzcrank", "lanes": ["Support", "Jungle"], "lolid": "0053" },
		{ "name": "Brand", "lanes": ["Support", "Mid"], "lolid": "0063" },
		{ "name": "Braum", "lanes": ["Support"], "lolid": "0201" },
		{ "name": "Caitlyn", "lanes": ["ADC"], "lolid": "0051" },
		{ "name": "Camille", "lanes": ["Top"], "lolid": "0164" },
		{ "name": "Cassiopeia", "lanes": ["Mid"], "lolid": "0069" },
		{ "name": "Cho'Gath", "lanes": ["Top", "Mid"], "lolid": "0031" },
		{ "name": "Corki", "lanes": ["Mid"], "lolid": "0042" },
		{ "name": "Darius", "lanes": ["Top"], "lolid": "0122" },
		{ "name": "Diana", "lanes": ["Jungle", "Mid"], "lolid": "0131" },
		{ "name": "Dr. Mundo", "lanes": ["Top", "Jungle"], "lolid": "0036" },
		{ "name": "Draven", "lanes": ["ADC"], "lolid": "0119" },
		{ "name": "Ekko", "lanes": ["Jungle", "Mid"], "lolid": "0245" },
		{ "name": "Elise", "lanes": ["Jungle"], "lolid": "0060" },
		{ "name": "Evelynn", "lanes": ["Jungle"], "lolid": "0028" },
		{ "name": "Ezreal", "lanes": ["ADC"], "lolid": "0081" },
		{ "name": "Fiddlesticks", "lanes": ["Jungle"], "lolid": "0009" },
		{ "name": "Fiora", "lanes": ["Top"], "lolid": "0114" },
		{ "name": "Fizz", "lanes": ["Mid"], "lolid": "0105" },
		{ "name": "Galio", "lanes": ["Mid", "Support"], "lolid": "0003" },
		{ "name": "Gangplank", "lanes": ["Mid", "Top"] },
		{ "name": "Garen", "lanes": ["Top"], "lolid": "0041" },
		{ "name": "Gnar", "lanes": ["Top"], "lolid": "0150" },
		{ "name": "Gragas", "lanes": ["Top", "Jungle"], "lolid": "0079" },
		{ "name": "Graves", "lanes": ["Jungle"], "lolid": "0104" },
		{ "name": "Gwen", "lanes": ["Top", "Jungle"], "lolid": "0887" },
		{ "name": "Hecarim", "lanes": ["Jungle"], "lolid": "0120" },
		{ "name": "Heimerdinger", "lanes": ["Mid", "Top", "Support"], "lolid": "0074" },
		{ "name": "Illaoi", "lanes": ["Top"], "lolid": "0420" },
		{ "name": "Irelia", "lanes": ["Top", "Mid"], "lolid": "0039" },
		{ "name": "Ivern", "lanes": ["Jungle"], "lolid": "0427" },
		{ "name": "Janna", "lanes": ["Support"], "lolid": "0040" },
		{ "name": "Jarvan IV", "lanes": ["Jungle"], "lolid": "0059" },
		{ "name": "Jax", "lanes": ["Top", "Jungle"], "lolid": "0024" },
		{ "name": "Jayce", "lanes": ["Top", "Mid"], "lolid": "0126" },
		{ "name": "Jhin", "lanes": ["ADC"], "lolid": "0202" },
		{ "name": "Jinx", "lanes": ["ADC"], "lolid": "0222" },
		{ "name": "Kai'Sa", "lanes": ["ADC"], "lolid": "0145" },
		{ "name": "Kalista", "lanes": ["ADC"], "lolid": "0429" },
		{ "name": "Karma", "lanes": ["Support"], "lolid": "0043" },
		{ "name": "Karthus", "lanes": ["Jungle", "ADC"], "lolid": "0030" },
		{ "name": "Kassadin", "lanes": ["Mid"], "lolid": "0038" },
		{ "name": "Katarina", "lanes": ["Mid"], "lolid": "0055" },
		{ "name": "Kayle", "lanes": ["Top"], "lolid": "0010" },
		{ "name": "Kayn", "lanes": ["Jungle"], "lolid": "0141" },
		{ "name": "Kennen", "lanes": ["Top", "Mid"], "lolid": "0017" },
		{ "name": "Kha'Zix", "lanes": ["Jungle"], "lolid": "0121" },
		{ "name": "Kindred", "lanes": ["Jungle"], "lolid": "0203" },
		{ "name": "Kled", "lanes": ["Top"], "lolid": "0240" },
		{ "name": "Kog'Maw", "lanes": ["ADC"], "lolid": "0096" },
		{ "name": "K'Sante", "lanes": ["Top"], "lolid": "0897" },
		{ "name": "LeBlanc", "lanes": ["Mid"], "lolid": "0007" },
		{ "name": "Lee Sin", "lanes": ["Jungle"], "lolid": "0064" },
		{ "name": "Leona", "lanes": ["Support"], "lolid": "0089" },
		{ "name": "Lillia", "lanes": ["Top", "Jungle"], "lolid": "0876" },
		{ "name": "Lissandra", "lanes": ["Mid"], "lolid": "0127" },
		{ "name": "Lucian", "lanes": ["ADC", "Top", "Mid"], "lolid": "0236" },
		{ "name": "Lulu", "lanes": ["Support"], "lolid": "0117" },
		{ "name": "Lux", "lanes": ["Mid", "Support"], "lolid": "0099" },
		{ "name": "Malphite", "lanes": ["Top", "Mid"], "lolid": "0054" },
		{ "name": "Malzahar", "lanes": ["Mid"], "lolid": "0090" },
		{ "name": "Maokai", "lanes": ["Top", "Support", "Jungle"], "lolid": "0057" },
		{ "name": "Master Yi", "lanes": ["Jungle"], "lolid": "0011" },
		{ "name": "Miss Fortune", "lanes": ["ADC", "Support"], "lolid": "0021" },
		{ "name": "Mordekaiser", "lanes": ["Top", "Jungle"], "lolid": "0082" },
		{ "name": "Morgana", "lanes": ["Support"], "lolid": "0025" },
		{ "name": "Nami", "lanes": ["Support"], "lolid": "0267" },
		{ "name": "Nasus", "lanes": ["Top"], "lolid": "0075" },
		{ "name": "Nautilus", "lanes": ["Support"], "lolid": "0111" },
		{ "name": "Neeko", "lanes": ["Mid", "Top", "Support"], "lolid": "0518" },
		{ "name": "Nidalee", "lanes": ["Jungle"], "lolid": "0076" },
		{ "name": "Nilah", "lanes": ["ADC"], "lolid": "0895" },
		{ "name": "Nocturne", "lanes": ["Jungle", "Top", "Mid"], "lolid": "0056" },
		{ "name": "Nunu & Willump", "lanes": ["Jungle"], "lolid": "0020" },
		{ "name": "Olaf", "lanes": ["Jungle", "Top"], "lolid": "0002" },
		{ "name": "Orianna", "lanes": ["Mid"], "lolid": "0061" },
		{ "name": "Ornn", "lanes": ["Top"], "lolid": "0516" },
		{ "name": "Pantheon", "lanes": ["Mid", "Support", "Top"], "lolid": "0080" },
		{ "name": "Poppy", "lanes": ["Top", "Jungle", "Support"], "lolid": "0078" },
		{ "name": "Pyke", "lanes": ["Support", "Mid"], "lolid": "0555" },
		{ "name": "Qiyana", "lanes": ["Mid"], "lolid": "0246" },
		{ "name": "Quinn", "lanes": ["Top"], "lolid": "0133" },
		{ "name": "Rakan", "lanes": ["Support"], "lolid": "0497" },
		{ "name": "Rammus", "lanes": ["Jungle"], "lolid": "0033" },
		{ "name": "Rek'Sai", "lanes": ["Jungle"], "lolid": "0421" },
		{ "name": "Rell", "lanes": ["Support"], "lolid": "0526" },
		{ "name": "Renata Glasc", "lanes": ["Support"], "lolid": "0888" },
		{ "name": "Renekton", "lanes": ["Top", "Mid"], "lolid": "0058" },
		{ "name": "Rengar", "lanes": ["Top", "Jungle"], "lolid": "0107" },
		{ "name": "Riven", "lanes": ["Top"], "lolid": "0092" },
		{ "name": "Rumble", "lanes": ["Top", "Mid"], "lolid": "0068" },
		{ "name": "Ryze", "lanes": ["Mid", "Top"], "lolid": "0013" },
		{ "name": "Samira", "lanes": ["ADC"], "lolid": "0360" },
		{ "name": "Sejuani", "lanes": ["Jungle", "Top"], "lolid": "0113" },
		{ "name": "Senna", "lanes": ["Support"], "lolid": "0235" },
		{ "name": "Seraphine", "lanes": ["Mid", "Support", "ADC"], "lolid": "0147" },
		{ "name": "Sett", "lanes": ["Top"], "lolid": "0875" },
		{ "name": "Shaco", "lanes": ["Jungle"], "lolid": "0035" },
		{ "name": "Shen", "lanes": ["Top"], "lolid": "0875" },
		{ "name": "Shyvana", "lanes": ["Jungle", "Top"], "lolid": "0102" },
		{ "name": "Singed", "lanes": ["Top", "Mid"], "lolid": "0027" },
		{ "name": "Sion", "lanes": ["Top"], "lolid": "0014" },
		{ "name": "Sivir", "lanes": ["ADC"], "lolid": "0015" },
		{ "name": "Skarner", "lanes": ["Jungle", "Top"], "lolid": "0072" },
		{ "name": "Sona", "lanes": ["Support"], "lolid": "0037" },
		{ "name": "Soraka", "lanes": ["Support"], "lolid": "0016" },
		{ "name": "Swain", "lanes": ["Mid", "Support"], "lolid": "0050" },
		{ "name": "Sylas", "lanes": ["Mid"], "lolid": "0517" },
		{ "name": "Syndra", "lanes": ["Mid"], "lolid": "0134" },
		{ "name": "Tahm Kench", "lanes": ["Top", "Support"], "lolid": "0223" },
		{ "name": "Taliyah", "lanes": ["Jungle", "Mid"], "lolid": "0163" },
		{ "name": "Talon", "lanes": ["Mid", "Jungle"], "lolid": "0091" },
		{ "name": "Taric", "lanes": ["Support"], "lolid": "0044" },
		{ "name": "Teemo", "lanes": ["Top"], "lolid": "0017" },
		{ "name": "Thresh", "lanes": ["Support"], "lolid": "0412" },
		{ "name": "Tristana", "lanes": ["ADC"], "lolid": "0018" },
		{ "name": "Trundle", "lanes": ["Jungle", "Top"], "lolid": "0048" },
		{ "name": "Tryndamere", "lanes": ["Top", "Mid"], "lolid": "0023" },
		{ "name": "Twisted Fate", "lanes": ["Mid"], "lolid": "0004" },
		{ "name": "Twitch", "lanes": ["ADC", "Support", "Mid"], "lolid": "0029" },
		{ "name": "Udyr", "lanes": ["Jungle", "Top"], "lolid": "0077" },
		{ "name": "Urgot", "lanes": ["Top"], "lolid": "0006" },
		{ "name": "Varus", "lanes": ["ADC", "Mid"], "lolid": "0110" },
		{ "name": "Vayne", "lanes": ["ADC", "Top"], "lolid": "0067" },
		{ "name": "Veigar", "lanes": ["Mid", "ADC"], "lolid": "0045" },
		{ "name": "Vel'Koz", "lanes": ["Mid", "Support"], "lolid": "0161" },
		{ "name": "Vex", "lanes": ["Mid"], "lolid": "0711" },
		{ "name": "Vi", "lanes": ["Jungle"], "lolid": "0254" },
		{ "name": "Viego", "lanes": ["Jungle"], "lolid": "0234" },
		{ "name": "Viktor", "lanes": ["Mid"], "lolid": "0112" },
		{ "name": "Vladimir", "lanes": ["Mid", "Top"], "lolid": "0008" },
		{ "name": "Volibear", "lanes": ["Top", "Jungle"], "lolid": "0106" },
		{ "name": "Warwick", "lanes": ["Jungle", "Top"], "lolid": "0019" },
		{ "name": "Wukong", "lanes": ["Top", "Jungle"], "lolid": "0062" },
		{ "name": "Xayah", "lanes": ["ADC"], "lolid": "0498" },
		{ "name": "Xerath", "lanes": ["Mid", "Support"], "lolid": "0101" },
		{ "name": "Xin Zhao", "lanes": ["Jungle"], "lolid": "0005" },
		{ "name": "Yasuo", "lanes": ["Mid", "Top"], "lolid": "0157" },
		{ "name": "Yone", "lanes": ["Mid", "Top"], "lolid": "0777" },
		{ "name": "Yorick", "lanes": ["Top"], "lolid": "0083" },
		{ "name": "Yuumi", "lanes": ["Support"], "lolid": "0350" },
		{ "name": "Zac", "lanes": ["Jungle"], "lolid": "0154" },
		{ "name": "Zed", "lanes": ["Mid", "Jungle"], "lolid": "0238" },
		{ "name": "Zeri", "lanes": ["ADC"], "lolid": "0221" },
		{ "name": "Ziggs", "lanes": ["ADC", "Mid"], "lolid": "0115" },
		{ "name": "Zilean", "lanes": ["Mid", "Support"], "lolid": "0026" },
		{ "name": "Zoe", "lanes": ["Mid"], "lolid": "0142" },
		{ "name": "Zyra", "lanes": ["Support"], "lolid": "0143" }
	]
};

export const cc = {
	"champions": [
		{ "name": "Aatrox", "cc": [{"key": "Q", "name": "The Darkin Blade", "desc": "Aatrox performs a strike with his greatsword for each of the three casts, dealing <span class='ad'>physical damage</span> to enemies hit within an area. Enemies hit within a Sweetspot of the area take <img src='/ext/icons/inlines/crit.png' class='inlineicon'> <span class='crit'>60% bonus damage</span> and also <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'>knocked up</span> for 0.25 seconds. Each subsequent cast increases The Darkin Blade's damage by 25%."}, { "key": "W", "name": "Infernal Chains", "desc": "Aatrox sends a chain in the target direction that deals <span class='ad'>physical damage</span> to the first enemy hit, doubled against minions, and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowing</span> them by 25% for 1.5 seconds. If the tether is not broken by the end of its duration, the target is dealt the same <span class='ad'>physical damage</span> again and <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'>pulled</span> to the center of the area." }] },
		{ "name": "Ahri", "cc": [{ "key": "E", "name": "Charm", "desc": "Ahri blows forth a kiss in the target direction that deals <span class='ap'>magic damage</span> to the first enemy hit, <img src='/ext/icons/inlines/knockdown.png' class='inlineicon'> <span class='knockdown'>knocking them down</span> and <img src='/ext/icons/inlines/charm.png' class='inlineicon'> <span class='charm'>charming</span> and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowing</span> them by 65% for a duration." }] },
		{ "name": "Akali", "cc": [{ "key": "Q", "name": "Five Point Strike", "desc": "Akali unleashes kunais in a cone in the target direction, dealing <span class='ap'>magic damage</span> to enemies hit. Targets at maximum range are also <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowed</span> by 50% for 0.5 seconds." }] },
		{ "name": "Akshan", "cc": [] },
		{ "name": "Alistar", "cc": [{ "key": "Q", "name": "Pulverize", "desc": "Alistar smashes the ground, dealing <span class='ap'>magic damage</span> to nearby enemies and <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>stunning</span> and <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'>knocking them up</span> simultaneously for 1 second." }, { "key": "W", "name": "Headbutt", "desc": "Alistar dashes to the target enemy's location. If they are within 400 units upon arrival, he deals them <span class='ap'>magic damage</span> and <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'>knocks them back</span> 700 units over 0.5 seconds while also <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>stunning them</span> for 0.75 seconds." }, { "key": "E", "name": "Trample", "desc": "Alistar tramples the ground around him every 0.5 seconds over 5 seconds, becoming <span class='ghost'>ghosted</span> and dealing <span class='ap'>magic damage</span> to nearby enemies. Each time this damages at least one enemy champion, he generates a stack of <i>Trample</i> that lasts for the remaining duration, stacking up to 5 times. At 5 stacks, Alistar's next basic attack against a champion within 6 seconds is empowered to deal <span class='ap'>20 − 275 (based on level) bonus magic damage</span> and <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>stun the target</span> for 1 second. This will end Trample prematurely." }] },
		{ "name": "Amumu", "cc": [{ "key": "Q", "name": "Bandage Toss", "desc": "Amumu throws a bandage in the target direction that deals <span class='ap'>magic damage</span> to the first enemy hit, <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>stunning them</span> for 1 second and pulling him to them, during which they are revealed." }, { "key": "R", "name": "Curse of the Sad Mummy", "desc": "Amumu entangles nearby enemies in bandages, dealing <span class='ap'>magic damage</span> as well as <img src='/ext/icons/inlines/knockdown.png' class='inlineicon'> <span class='knockdown'>knocking down</span> and <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>stunning them</span> for 1.5 seconds." }] },
		{ "name": "Anivia", "cc": [{ "key": "Q", "name": "Flash Frost", "desc": "Anivia launches a chunk of ice in the target direction that deals <span class='ap'>magic damage</span> to enemies hit and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slows them</span> by 20% − 40% (based on Glacial Storm's Rank) for 3 seconds. On recast, Anivia shatters the ice, dealing <span class='ap'>magic damage</span> to nearby enemies and <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>stunning them</span> for a duration, as well as refreshing the <img src='/ext/icons/inlines/slow.png' class='inlineicon'> slow." }, {"key": "W", "name": "Crystallize", "desc": "Anivia summons a wall of ice at the target location perpendicular to her, <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'>knocking all units away</span> from it, though not through terrain. The wall lingers as impassable terrain for 5 seconds." }, { "key": "R", "name": "Glacial Storm", "desc": "Anivia calls forth a driving rain of ice and hail at the target location, dealing <span class='ap'>magic damage</span> every 0.5 seconds to enemies within and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowing them</span> for 1 second, refreshing every 0.5 seconds while they remain inside." }] },
		{ "name": "Annie", "cc": [{ "key": "P", "name": "Pyromania", "desc": "Annie generates a stack of <i>Pyromania</i> whenever she hits an enemy with  Disintegrate or casts her other abilities, stacking up to 4 times, at which she gains Energized. When she is Energized, Annie empowers her next cast of Disintegrate, Incinerate, or Summon: Tibbers to consume all <i>Pyromania</i> stacks to <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>stun enemies hit</span> for 1.25 / 1.5 / 1.75 (based on level) seconds." }] },
		{ "name": "Aphelios", "cc": [{ "key": "P", "name": "Gravitum", "desc": "Basic attacks with <i>Gravitum</i> <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slow enemies</span> by 30% for 3.5 seconds, decaying to 10% after 0.7 seconds." }, { "key": "Q", "name": "Gravitum - Active", "desc": "Aphelios expunges all enemies with <i>Gravitum's</i> <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slow debuff</span>, dealing <span class='ap'>magic damage</span> and <img src='/ext/icons/inlines/root.png' class='inlineicon'> <span class='root'>rooting them</span> for 1 second." }, { "key": "R", "name": "Moonlight Vigil", "desc": "Increases the initial <img src='/ext/icons/inlines/slow.png' class='inlineicon'> slow to 99% and empowers Binding Eclipse to <img src='/ext/icons/inlines/root.png' class='inlineicon'> <span class='root'>root targets</span> affected by the enhanced slow for 1.35 seconds." }] },
		{ "name": "Ashe", "cc": [{ "key": "P", "name": "Frost Shot", "desc": "Ashe's basic attacks and ability hits apply Frost to enemies, which <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slows them</span> by 20% − 30% (based on level) for 2 seconds. Basic attacks against enemies with Frost are modified to deal 110% damage." }, { "key": "W", "name": "Volley", "desc": "Ashe shoots a volley of arrows in a cone in the target direction, each dealing <span class='ad'>physical damage</span> to the first enemy hit, and applying <i>Critical Slow</i> to enemy champions hit." }, { "key": "R", "name": "Enchanted Crystal Arrow", "desc": "Ashe fires a massive arrow of ice in the target direction, granting sight of the area it flies through each for 1 second. The arrow shatters upon hitting an enemy champion, dealing them <span class='ap'>magic damage</span>, <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>stunning them</span> for 1 − 3.5 (based on distance traveled) seconds, and granting sight of the area around them for 1 second." }] },
		{ "name": "Aurelion Sol", "cc": [{ "key": "Q", "name": "Starsurge", "desc": "Aurelion Sol fires a star in the target direction that expands as long as it remains within the Outer Limit, granting him <img src='/ext/icons/inlines/speed.png' class='inlineicon'> <span class='speed'>20% bonus movement speed</span> while active. If he moves faster than the star, the speed of the star will increase to stay within the Outer Limit. Starsurge can be recast after 0.25 seconds while the star is active, and does so automatically when the star travels beyond the Outer Limit. On recast, Aurelion Sol detonates the star, dealing <span class='ap'>magic damage</span> to nearby enemies and <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>stunning them</span> for a duration, which is increased by 0% − 300% (based on time traveled)." }, { "key": "R", "name": "Voice of Light" }] },
		{ "name": "Azir", "cc": [{ "key": "Q", "name": "Conquering Sands" }, { "key": "R", "name": "Emperor's Divide" }] },
		{ "name": "Bard", "cc": [{ "key": "Q", "name": "Cosmic Binding" }, { "key": "R", "name": "Tempered Fate" }] },
		{ "name": "Bel'Veth", "cc": [{ "key": "W", "name": "Above and Below" }] },
		{ "name": "Blitzcrank", "cc": [{ "key": "Q", "name": "Rocket Grab" }, { "key": "E", "name": "Power Fist" }, { "key": "R", "name": "Static Field" }] },
		{ "name": "Brand", "cc": [{ "key": "Q", "name": "Sear" }] },
		{ "name": "Braum", "cc": [{ "key": "P", "name": "Concussive Blows" }, { "key": "Q", "name": "Winter's Bite" }, { "key": "R", "name": "Glacial Fissure" }] },
		{ "name": "Caitlyn", "cc": [{ "key": "W", "name": "Yordle Snap Trap" }, { "key": "E", "name": "90 Caliber Net" }] },
		{ "name": "Camille", "cc": [{ "key": "W", "name": "Tactical Sweep" }, { "key": "E", "name": "Hookshot" }, { "key": "R", "name": "The Hextech Ultimatum" }] },
		{ "name": "Cassiopeia", "cc": [{ "key": "W", "name": "Miasma" }, { "key": "R", "name": "Petrifying Gaze" }] },
		{ "name": "Cho'Gath", "cc": [{ "key": "Q", "name": "Rupture" }, { "key": "W", "name": "Feral Scream" }, { "key": "E", "name": "Vorpal Spikes" }] },
		{ "name": "Corki", "cc": [{ "key": "W", "name": "Special Delivery" }] },
		{ "name": "Darius", "cc": [{ "key": "W", "name": "Crippling Strike" }, { "key": "E", "name": "Apprehend" }] },
		{ "name": "Diana", "cc": [{ "key": "R", "name": "Moonfall" }] },
		{ "name": "Dr. Mundo", "cc": [{ "key": "Q", "name": "Infected Bonesaw" }] },
		{ "name": "Draven", "cc": [{ "key": "E", "name": "Stand Aside" }] },
		{ "name": "Ekko", "cc": [{ "key": "Q", "name": "Timewinder" }, { "key": "W", "name": "Parallel Convergence" }] },
		{ "name": "Elise", "cc": [{ "key": "E", "name": "Cocoon" }] },
		{ "name": "Evelynn", "cc": [{ "key": "W", "name": "Allure" }] },
		{ "name": "Ezreal", "cc": [] },
		{ "name": "Fiddlesticks", "cc": [{ "key": "Q", "name": "Terrify" }, { "key": "E", "name": "Reap" }] },
		{ "name": "Fiora", "cc": [{ "key": "W", "name": "Riposte" }, { "key": "E", "name": "Bladework" }] },
		{ "name": "Fizz", "cc": [{ "key": "R", "name": "Chum the Waters" }] },
		{ "name": "Galio", "cc": [{ "key": "W", "name": "Shield of Durand" }, { "key": "E", "name": "Justice Punch" }, { "key": "R", "name": "Hero's Entrance" }] },
		{ "name": "Gangplank", "cc": [{ "key": "E", "name": "Powder Keg" }, { "key": "R", "name": "Cannon Barrage" }] },
		{ "name": "Garen", "cc": [{ "key": "Q", "name": "Decisive Strike" }] },
		{ "name": "Gnar", "cc": [{ "key": "Q", "name": "Boomerang Throw / Boulder Toss" }, { "key": "W", "name": "Wallop" }, { "key": "R", "name": "GNAR!" }] },
		{ "name": "Gragas", "cc": [{ "key": "Q", "name": "Barrel Roll" }, { "key": "E", "name": "Body Slam" }, { "key": "R", "name": "Explosive Cask" }] },
		{ "name": "Graves", "cc": [{ "key": "W", "name": "Smoke Screen" }] },
		{ "name": "Gwen", "cc": [{"key": "R", "name": "Needlework"}] },
		{ "name": "Hecarim", "cc": [{ "key": "E", "name": "Devastating Charge" }, { "key": "R", "name": "Onslaught of Shadows" }] },
		{ "name": "Heimerdinger", "cc": [{ "key": "E", "name": "CH-2 Electron Storm Grenade" }] },
		{ "name": "Illaoi", "cc": [{ "key": "E", "name": "Test of Spirit" }] },
		{ "name": "Irelia", "cc": [{ "key": "E", "name": "Flawless Duet" }, { "key": "R", "name": "Vanguard's Edge" }] },
		{ "name": "Ivern", "cc": [{ "key": "Q", "name": "Rootcaller" }, { "key": "E", "name": "Triggerseed" }, { "key": "R", "name": "Daisy!" }] },
		{ "name": "Janna", "cc": [{ "key": "Q", "name": "Howling Gale" }, { "key": "W", "name": "Zephyr" }, { "key": "R", "name": "Monsoon" }] },
		{ "name": "Jarvan IV", "cc": [{ "key": "Q", "name": "Dragon Strike" }, { "key": "W", "name": "Golden Aegis" }] },
		{ "name": "Jax", "cc": [{ "key": "E", "name": "Counter Strike" }] },
		{ "name": "Jayce", "cc": [{ "key": "Q", "name": "To the Skies!" }, { "key": "E", "name": "Thundering Blow" }] },
		{ "name": "Jhin", "cc": [{ "key": "W", "name": "Deadly Flourish" }, { "key": "E", "name": "Captive Audience" }, { "key": "R", "name": "Curtain Call" }] },
		{ "name": "Jinx", "cc": [{ "key": "W", "name": "Zap!" }, { "key": "E", "name": "Flame Chompers!" }] },
		{ "name": "Kai'Sa", "cc": [] },
		{ "name": "Kalista", "cc": [{"key": "E", "name": "Rend"}, { "key": "R", "name": "Fate's Call" }] },
		{ "name": "Karma", "cc": [{ "key": "Q", "name": "Inner Flame" }, { "key": "E", "name": "Focused Resolve" }] },
		{ "name": "Karthus", "cc": [{ "key": "W", "name": "Wall of Pain" }] },
		{ "name": "Kassadin", "cc": [{ "key": "E", "name": "Force Pulse" }] },
		{ "name": "Katarina", "cc": [] },
		{ "name": "Kayle", "cc": [{ "key": "Q", "name": "Radiant Blast" }] },
		{ "name": "Kayn", "cc": [{ "key": "W", "name": "Blade's Reach" }] },
		{ "name": "Kennen", "cc": [{ "key": "P", "name": "Mark of the Storm" }] },
		{ "name": "Kha'Zix", "cc": [{ "key": "P", "name": "Unseen Threat" }, { "key": "W", "name": "Evolved Spike Racks" }] },
		{ "name": "Kindred", "cc": [{ "key": "E", "name": "Mounting Dread" }] },
		{ "name": "Kled", "cc": [{ "key": "Q", "name": "Bear Trap on a Rope" }, { "key": "R", "name": "CHAAAAAAAARGE!!!" }] },
		{ "name": "Kog'Maw", "cc": [{ "key": "E", "name": "Void Ooze" }] },
		{ "name": "K'Sante", "cc": [{ "key": "Q", "name": "Ntofo Strikes" }, { "key": "W", "name": "Path Maker" }, { "key": "R", "name": "All Out" }] },
		{ "name": "LeBlanc", "cc": [{ "key": "E", "name": "Ethereal Chains" }] },
		{ "name": "Lee Sin", "cc": [{ "key": "E", "name": "Cripple" }, { "key": "R", "name": "Dragon's Rage" }] },
		{ "name": "Leona", "cc": [{ "key": "Q", "name": "Shield of Daybreak" }, { "key": "E", "name": "Zenith Blade" }, { "key": "R", "name": "Solar Flare" }] },
		{ "name": "Lillia", "cc": [{ "key": "E", "name": "Swirlseed" }, { "key": "R", "name": "Lilting Lullaby" }] },
		{ "name": "Lissandra", "cc": [{ "key": "P", "name": "Iceborn Subjugation" }, { "key": "Q", "name": "Ice Shard" }, { "key": "W", "name": "Ring of Frost" }, { "key": "R", "name": "Frozen Tomb" }] },
		{ "name": "Lucian", "cc": [] },
		{ "name": "Lulu", "cc": [{ "key": "Q", "name": "Glitterlance" }, { "key": "W", "name": "Whimsy" }, { "key": "R", "name": "Wild Growth" }] },
		{ "name": "Lux", "cc": [{ "key": "Q", "name": "Light Binding" }, { "key": "E", "name": "Lucent Singularity" }] },
		{ "name": "Malphite", "cc": [{ "key": "Q", "name": "Seismic Shard" }, { "key": "R", "name": "Unstoppable Force" }] },
		{ "name": "Malzahar", "cc": [{ "key": "Q", "name": "Call of the Void" }, { "key": "R", "name": "Nether Grasp" }] },
		{ "name": "Maokai", "cc": [{ "key": "Q", "name": "Bramble Smash" }, { "key": "W", "name": "Twisted Advance" }, {"key": "E", "name": "Sapling Toss"}, { "key": "R", "name": "Nature's Grasp" }] },
		{ "name": "Master Yi", "cc": [] },
		{ "name": "Miss Fortune", "cc": [{ "key": "E", "name": "Make it Rain" }] },
		{ "name": "Mordekaiser", "cc": [{ "key": "E", "name": "Death's Grasp" }, { "key": "R", "name": "Realm of Death" }] },
		{ "name": "Morgana", "cc": [{ "key": "Q", "name": "Dark Binding" }, { "key": "R", "name": "Soul Shackles" }] },
		{ "name": "Nami", "cc": [{ "key": "Q", "name": "Aqua Prison" }, { "key": "E", "name": "Tidecaller's Blessing" }, { "key": "R", "name": "Tidal Wave" }] },
		{ "name": "Nasus", "cc": [{ "key": "W", "name": "Wither" }] },
		{ "name": "Nautilus", "cc": [{ "key": "P", "name": "Staggering Blow" }, { "key": "Q", "name": "Dredge Line" }, { "key": "E", "name": "Riptide" }, { "key": "R", "name": "Depth Charge" }] },
		{ "name": "Neeko", "cc": [{ "key": "E", "name": "Tangle-Barbs" }, { "key": "R", "name": "Pop Blossom" }] },
		{ "name": "Nidalee", "cc": [] },
		{ "name": "Nilah", "cc": [{ "key": "R", "name": "Apotheosis" }] },
		{ "name": "Nocturne", "cc": [{ "key": "E", "name": "Unspeakable Horror" }, { "key": "R", "name": "Paranoia" }] },
		{ "name": "Nunu & Willump", "cc": [{ "key": "W", "name": "Biggest Snowball Ever!" }, { "key": "E", "name": "Snowball Barrage" }, { "key": "R", "name": "Absolute Zero" }] },
		{ "name": "Olaf", "cc": [{ "key": "Q", "name": "Undertow" }] },
		{ "name": "Orianna", "cc": [{ "key": "W", "name": "Command: Dissonance" }, { "key": "R", "name": "Command: Shockwave" }] },
		{ "name": "Ornn", "cc": [{ "key": "Q", "name": "Volcanic Rupture" }, { "key": "E", "name": "Searing Charge" }, { "key": "R", "name": "Call of the Forge God" }] },
		{ "name": "Pantheon", "cc": [{ "key": "W", "name": "Shield Vault" }] },
		{ "name": "Poppy", "cc": [{ "key": "Q", "name": "Hammer Shock" }, { "key": "W", "name": "Steadfast Presence" }, { "key": "E", "name": "Heroic Charge" }, { "key": "R", "name": "Keeper's Verdict" }] },
		{ "name": "Pyke", "cc": [{ "key": "Q", "name": "Bone Skewer" }, { "key": "E", "name": "Phantom Undertow" }] },
		{ "name": "Qiyana", "cc": [{ "key": "R", "name": "Supreme Display of Talent" }] },
		{ "name": "Quinn", "cc": [{ "key": "E", "name": "Vault" }] },
		{ "name": "Rakan", "cc": [{ "key": "W", "name": "Grand Entrance" }, { "key": "R", "name": "The Quickness" }] },
		{ "name": "Rammus", "cc": [{ "key": "Q", "name": "Powerball" }, { "key": "E", "name": "Frenzying Taunt" }, { "key": "R", "name": "Soaring Slam" }] },
		{ "name": "Rek'Sai", "cc": [{ "key": "W", "name": "Un-Burrow" }] },
		{ "name": "Rell", "cc": [{ "key": "W", "name": "Ferromancy: Crash Down" }, { "key": "E", "name": "Attract and Repel" }, { "key": "R", "name": "Magnet Storm" }] },
		{ "name": "Renata Glasc", "cc": [{ "key": "Q", "name": "Handshake" }, { "key": "E", "name": "Loyalty Program" }, { "key": "R", "name": "Hostile Takeover" }] },
		{ "name": "Renekton", "cc": [{ "key": "W", "name": "Ruthless Predator" }] },
		{ "name": "Rengar", "cc": [{ "key": "E", "name": "Bola Strike" }] },
		{ "name": "Riven", "cc": [{ "key": "Q", "name": "Broken Wings" }, { "key": "W", "name": "Ki Burst" }] },
		{ "name": "Rumble", "cc": [{ "key": "E", "name": "Electro Harpoon" }, { "key": "R", "name": "The Equalizer" }] },
		{ "name": "Ryze", "cc": [{ "key": "W", "name": "Rune Prison" }] },
		{ "name": "Samira", "cc": [{ "key": "P", "name": "Daredevil Impulsive" }] },
		{ "name": "Sejuani", "cc": [{ "key": "Q", "name": "Arctic Assault" }, { "key": "W", "name": "Winter's Wrath" }, { "key": "E", "name": "Permafrost" }, { "key": "R", "name": "Glacial Prison" }] },
		{ "name": "Senna", "cc": [{ "key": "Q", "name": "Piercing Darkness" }, { "key": "W", "name": "Last Embrace" }] },
		{ "name": "Seraphine", "cc": [{ "key": "E", "name": "Beat Drop" }, { "key": "R", "name": "Encore" }] },
		{ "name": "Sett", "cc": [{ "key": "E", "name": "Facebreaker" }, { "key": "R", "name": "The Show Stopper" }] },
		{ "name": "Shaco", "cc": [{ "key": "W", "name": "Jack in the Box" }, { "key": "E", "name": "Two-Shiv Poison" }, { "key": "R", "name": "Hallucinate" }] },
		{ "name": "Shen", "cc": [{ "key": "Q", "name": "Twilight Assault" }, { "key": "E", "name": "Shadow Dash" }] },
		{ "name": "Shyvana", "cc": [{ "key": "R", "name": "Dragon's Descent" }] },
		{ "name": "Singed", "cc": [{ "key": "W", "name": "Mega Adhesive" }, { "key": "E", "name": "Fling" }] },
		{ "name": "Sion", "cc": [{ "key": "Q", "name": "Decimating Smash" }, { "key": "E", "name": "Roar of the Slayer" }, { "key": "R", "name": "Unstoppable Onslaught" }] },
		{ "name": "Sivir", "cc": [] },
		{ "name": "Skarner", "cc": [{ "key": "E", "name": "Fracture" }, { "key": "R", "name": "Impale" }] },
		{ "name": "Sona", "cc": [{ "key": "E", "name": "Song of Celerity" }, { "key": "R", "name": "Crescendo" }] },
		{ "name": "Soraka", "cc": [{ "key": "Q", "name": "Starcall" }, { "key": "E", "name": "Equinox" }] },
		{ "name": "Swain", "cc": [{ "key": "W", "name": "Vision of Empire" }, { "key": "E", "name": "Nevermove" }, { "key": "R", "name": "Demonic Ascension" }] },
		{ "name": "Sylas", "cc": [{ "key": "Q", "name": "Chain Lash" }, { "key": "E", "name": "Abduct" }] },
		{ "name": "Syndra", "cc": [{ "key": "W", "name": "Force of Will" }, { "key": "E", "name": "Scatter the Weak" }] },
		{ "name": "Tahm Kench", "cc": [{ "key": "Q", "name": "Tongue Lash" }, { "key": "W", "name": "Abyssal Dive" }, { "key": "R", "name": "Devour" }] },
		{ "name": "Taliyah", "cc": [{ "key": "Q", "name": "Threaded Volley" }, { "key": "W", "name": "Seismic Shove" }, { "key": "E", "name": "Unraveled Earth" }, { "key": "R", "name": "Weaver's Wall" }] },
		{ "name": "Talon", "cc": [{ "key": "W", "name": "Rake" }] },
		{ "name": "Taric", "cc": [{ "key": "E", "name": "Dazzle" }] },
		{ "name": "Teemo", "cc": [{ "key": "Q", "name": "Blinding Dart" }, { "key": "R", "name": "Noxious Trap" }] },
		{ "name": "Thresh", "cc": [{ "key": "Q", "name": "Death Sentence" }, { "key": "E", "name": "Flay" }, { "key": "R", "name": "The Box" }] },
		{ "name": "Tristana", "cc": [{ "key": "W", "name": "Rocket Jump" }, { "key": "R", "name": "Buster Shot" }] },
		{ "name": "Trundle", "cc": [{ "key": "Q", "name": "Chomp" }, { "key": "E", "name": "Pillar of Ice" }] },
		{ "name": "Tryndamere", "cc": [{ "key": "W", "name": "Mocking Shout" }] },
		{ "name": "Twisted Fate", "cc": [{ "key": "W", "name": "Pick A Card - Red and Gold" }] },
		{ "name": "Twitch", "cc": [{ "key": "W", "name": "Venom Cask" }] },
		{ "name": "Udyr", "cc": [{ "key": "E", "name": "Blazing Stampede" }, { "key": "R", "name": "Wingborne Storm" }] },
		{ "name": "Urgot", "cc": [{ "key": "Q", "name": "Corrosive Charge" }, { "key": "E", "name": "Disdain" }, { "key": "R", "name": "Fear Beyond Death" }] },
		{ "name": "Varus", "cc": [{ "key": "E", "name": "Hail of Arrows" }, { "key": "R", "name": "Chain of Corruption" }] },
		{ "name": "Vayne", "cc": [{ "key": "E", "name": "Condemn" }] },
		{ "name": "Veigar", "cc": [{ "key": "E", "name": "Event Horizon" }] },
		{ "name": "Vel'Koz", "cc": [{ "key": "Q", "name": "Plasma Fission" }, { "key": "E", "name": "Tectonic Disruption" }] },
		{ "name": "Vex", "cc": [{ "key": "P", "name": "Doom 'N Gloom" }, { "key": "E", "name": "Looming Darkness" }] },
		{ "name": "Vi", "cc": [{ "key": "Q", "name": "Vault Breaker" }, { "key": "R", "name": "Cease and Desist" }] },
		{ "name": "Viego", "cc": [{ "key": "W", "name": "Spectral Maw" }, { "key": "R", "name": "Heartbreaker" }] },
		{ "name": "Viktor", "cc": [{ "key": "W", "name": "Gravity Field" }] },
		{ "name": "Vladimir", "cc": [{ "key": "W", "name": "Sanguine Pool" }] },
		{ "name": "Volibear", "cc": [{ "key": "Q", "name": "Thundering Smash" }, { "key": "E", "name": "Sky Splitter" }, { "key": "R", "name": "Stormbringer" }] },
		{ "name": "Warwick", "cc": [{ "key": "E", "name": "Primal Howl" }, { "key": "R", "name": "Infinite Duress" }] },
		{ "name": "Wukong", "cc": [{ "key": "R", "name": "Cyclone" }] },
		{ "name": "Xayah", "cc": [{ "key": "E", "name": "Bladecaller" }] },
		{ "name": "Xerath", "cc": [{ "key": "W", "name": "Eye of Destruction" }, { "key": "E", "name": "Shocking Orb" }] },
		{ "name": "Xin Zhao", "cc": [{ "key": "Q", "name": "Three Talon Strike" }, { "key": "W", "name": "Wind Becomes Lightning" }, { "key": "E", "name": "Audacious Charge" }, { "key": "R", "name": "Crescent Guard" }] },
		{ "name": "Yasuo", "cc": [{ "key": "Q", "name": "Steel Tempest" }, { "key": "R", "name": "Last Breath" }] },
		{ "name": "Yone", "cc": [{ "key": "Q", "name": "Mortal Steel" }, { "key": "R", "name": "Fate Sealed" }] },
		{ "name": "Yorick", "cc": [{ "key": "W", "name": "Dark Procession" }, { "key": "E", "name": "Mourning Mist" }] },
		{ "name": "Yuumi", "cc": [{ "key": "Q", "name": "Prowling Projectile" }, { "key": "R", "name": "Final Chapter" }] },
		{ "name": "Zac", "cc": [{ "key": "Q", "name": "Stretching Strikes" }, { "key": "E", "name": "Elastic Slingshot" }, { "key": "R", "name": "Let's Bounce" }] },
		{ "name": "Zed", "cc": [] },
		{ "name": "Zeri", "cc": [{ "key": "W", "name": "Ultrashock Laser" }] },
		{ "name": "Ziggs", "cc": [{ "key": "W", "name": "Satchel Charge" }, { "key": "E", "name": "Hexplosive Minefield" }] },
		{ "name": "Zilean", "cc": [{ "key": "Q", "name": "Time Bomb" }, { "key": "E", "name": "Time Warp" }] },
		{ "name": "Zoe", "cc": [{ "key": "W", "name": "Spell Thief" }, { "key": "E", "name": "Sleepy Trouble Bubble" }] },
		{ "name": "Zyra", "cc": [{ "key": "E", "name": "Grasping Roots" }, { "key": "R", "name": "Stranglethorns" }] }
	]
};

export const cancels = {
	"champions": [
		{ "name": "Aatrox", "cc": [{"key": "Q", "name": "The Darkin Blade"}, { "key": "W", "name": "Infernal Chains" }] },
		{ "name": "Ahri", "cc": [{ "key": "E", "name": "Charm" }] },
		{ "name": "Alistar", "cc": [{ "key": "Q", "name": "Pulverize" }, { "key": "W", "name": "Headbutt" }, { "key": "E", "name": "Trample" }] },
		{ "name": "Amumu", "cc": [{ "key": "Q", "name": "Bandage Toss" }, { "key": "R", "name": "Curse of the Sad Mummy" }] },
		{ "name": "Anivia", "cc": [{ "key": "Q", "name": "Flash Frost" }, {"key": "W", "name": "Crystallize"}] },
		{ "name": "Annie", "cc": [{ "key": "P", "name": "Pyromania"}] },
		{ "name": "Aphelios", "cc": [{ "key": "Q", "name": "Gravitum - Active" }, { "key": "R", "name": "Moonlight Vigil" }] },
		{ "name": "Ashe", "cc": [{ "key": "R", "name": "Enchanted Crystal Arrow" }] },
		{ "name": "Aurelion Sol", "cc": [{ "key": "Q", "name": "Starsurge" }, { "key": "R", "name": "Voice of Light" }] },
		{ "name": "Azir", "cc": [{ "key": "R", "name": "Emperor's Divide" }] },
		{ "name": "Bard", "cc": [{ "key": "Q", "name": "Cosmic Binding" }, { "key": "R", "name": "Tempered Fate" }] },
		{ "name": "Bel'Veth", "cc": [{ "key": "W", "name": "Above and Below" }] },
		{ "name": "Blitzcrank", "cc": [{ "key": "Q", "name": "Rocket Grab" }, { "key": "E", "name": "Power Fist" }] },
		{ "name": "Brand", "cc": [{ "key": "Q", "name": "Sear" }] },
		{ "name": "Braum", "cc": [{ "key": "P", "name": "Concussive Blows" }, { "key": "R", "name": "Glacial Fissure" }] },
		{ "name": "Caitlyn", "cc": [{ "key": "W", "name": "Yordle Snap Trap" }] },
		{ "name": "Camille", "cc": [{ "key": "E", "name": "Hookshot" }, { "key": "R", "name": "The Hextech Ultimatum" }] },
		{ "name": "Cassiopeia", "cc": [{ "key": "W", "name": "Miasma" }, { "key": "R", "name": "Petrifying Gaze" }] },
		{ "name": "Cho'Gath", "cc": [{ "key": "Q", "name": "Rupture" }] },
		{ "name": "Corki", "cc": [{ "key": "W", "name": "Special Delivery" }] },
		{ "name": "Darius", "cc": [{ "key": "E", "name": "Apprehend" }] },
		{ "name": "Diana", "cc": [{ "key": "R", "name": "Moonfall" }] },
		{ "name": "Draven", "cc": [{ "key": "E", "name": "Stand Aside" }] },
		{ "name": "Ekko", "cc": [{ "key": "W", "name": "Parallel Convergence" }] },
		{ "name": "Elise", "cc": [{ "key": "E", "name": "Cocoon" }] },
		{ "name": "Evelynn", "cc": [{ "key": "W", "name": "Allure" }] },
		{ "name": "Fiddlesticks", "cc": [{ "key": "Q", "name": "Terrify" }] },
		{ "name": "Fiora", "cc": [{ "key": "W", "name": "Riposte" }] },
		{ "name": "Fizz", "cc": [{ "key": "R", "name": "Chum the Waters" }] },
		{ "name": "Galio", "cc": [{ "key": "W", "name": "Shield of Durand" }, { "key": "E", "name": "Justice Punch" }, { "key": "R", "name": "Hero's Entrance" }] },
		{ "name": "Gnar", "cc": [{ "key": "W", "name": "Wallop" }, { "key": "R", "name": "GNAR!" }] },
		{ "name": "Gragas", "cc": [{ "key": "E", "name": "Body Slam" }, { "key": "R", "name": "Explosive Cask" }] },
		{ "name": "Hecarim", "cc": [{ "key": "E", "name": "Devastating Charge" }, { "key": "R", "name": "Onslaught of Shadows" }] },
		{ "name": "Heimerdinger", "cc": [{ "key": "E", "name": "CH-2 Electron Storm Grenade" }] },
		{ "name": "Irelia", "cc": [{ "key": "E", "name": "Flawless Duet" }] },
		{ "name": "Ivern", "cc": [{ "key": "Q", "name": "Rootcaller" }, { "key": "R", "name": "Daisy!" }] },
		{ "name": "Janna", "cc": [{ "key": "Q", "name": "Howling Gale" }, { "key": "R", "name": "Monsoon" }] },
		{ "name": "Jarvan IV", "cc": [{ "key": "Q", "name": "Dragon Strike" }] },
		{ "name": "Jax", "cc": [{ "key": "E", "name": "Counter Strike" }] },
		{ "name": "Jayce", "cc": [{ "key": "E", "name": "Thundering Blow" }] },
		{ "name": "Jhin", "cc": [{ "key": "W", "name": "Deadly Flourish" }] },
		{ "name": "Jinx", "cc": [{ "key": "E", "name": "Flame Chompers!" }] },
		{ "name": "Kalista", "cc": [{ "key": "R", "name": "Fate's Call" }] },
		{ "name": "Karma", "cc": [{ "key": "E", "name": "Focused Resolve" }] },
		{ "name": "Kennen", "cc": [{ "key": "P", "name": "Mark of the Storm" }] },
		{ "name": "Kled", "cc": [{ "key": "Q", "name": "Bear Trap on a Rope" }, { "key": "R", "name": "CHAAAAAAAARGE!!!" }] },
		{ "name": "K'Sante", "cc": [{ "key": "Q", "name": "Ntofo Strikes" }, { "key": "W", "name": "Path Maker" }, { "key": "R", "name": "All Out" }] },
		{ "name": "LeBlanc", "cc": [{ "key": "E", "name": "Ethereal Chains" }] },
		{ "name": "Lee Sin", "cc": [{ "key": "R", "name": "Dragon's Rage" }] },
		{ "name": "Leona", "cc": [{ "key": "Q", "name": "Shield of Daybreak" }, { "key": "E", "name": "Zenith Blade" }, { "key": "R", "name": "Solar Flare" }] },
		{ "name": "Lillia", "cc": [{ "key": "R", "name": "Lilting Lullaby" }] },
		{ "name": "Lissandra", "cc": [{ "key": "W", "name": "Ring of Frost" }, { "key": "R", "name": "Frozen Tomb" }] },
		{ "name": "Lulu", "cc": [{ "key": "W", "name": "Whimsy" }, { "key": "R", "name": "Wild Growth" }] },
		{ "name": "Lux", "cc": [{ "key": "Q", "name": "Light Binding" }] },
		{ "name": "Malphite", "cc": [{ "key": "R", "name": "Unstoppable Force" }] },
		{ "name": "Malzahar", "cc": [{ "key": "R", "name": "Nether Grasp" }] },
		{ "name": "Maokai", "cc": [{ "key": "Q", "name": "Bramble Smash" }, { "key": "W", "name": "Twisted Advance" }, { "key": "R", "name": "Nature's Grasp" }] },
		{ "name": "Mordekaiser", "cc": [{ "key": "E", "name": "Death's Grasp" }] },
		{ "name": "Morgana", "cc": [{ "key": "Q", "name": "Dark Binding" }, { "key": "R", "name": "Soul Shackles" }] },
		{ "name": "Nami", "cc": [{ "key": "Q", "name": "Aqua Prison" }, { "key": "R", "name": "Tidal Wave" }] },
		{ "name": "Nautilus", "cc": [{ "key": "P", "name": "Staggering Blow" }, { "key": "Q", "name": "Dredge Line" }, { "key": "R", "name": "Depth Charge" }] },
		{ "name": "Neeko", "cc": [{ "key": "E", "name": "Tangle-Barbs" }, { "key": "R", "name": "Pop Blossom" }] },
		{ "name": "Nilah", "cc": [{ "key": "R", "name": "Apotheosis" }] },
		{ "name": "Nocturne", "cc": [{ "key": "E", "name": "Unspeakable Horror" }] },
		{ "name": "Nunu & Willump", "cc": [{ "key": "W", "name": "Biggest Snowball Ever!" }] },
		{ "name": "Orianna", "cc": [{ "key": "R", "name": "Command: Shockwave" }] },
		{ "name": "Ornn", "cc": [{ "key": "Q", "name": "Volcanic Rupture" }, { "key": "E", "name": "Searing Charge" }, { "key": "R", "name": "Call of the Forge God" }] },
		{ "name": "Pantheon", "cc": [{ "key": "W", "name": "Shield Vault" }] },
		{ "name": "Poppy", "cc": [{ "key": "W", "name": "Steadfast Presence" }, { "key": "E", "name": "Heroic Charge" }, { "key": "R", "name": "Keeper's Verdict" }] },
		{ "name": "Pyke", "cc": [{ "key": "Q", "name": "Bone Skewer" }, { "key": "E", "name": "Phantom Undertow" }] },
		{ "name": "Qiyana", "cc": [{ "key": "R", "name": "Supreme Display of Talent" }] },
		{ "name": "Quinn", "cc": [{ "key": "E", "name": "Vault" }] },
		{ "name": "Rakan", "cc": [{ "key": "W", "name": "Grand Entrance" }, { "key": "R", "name": "The Quickness" }] },
		{ "name": "Rammus", "cc": [{ "key": "Q", "name": "Powerball" }, { "key": "E", "name": "Frenzying Taunt" }, { "key": "R", "name": "Soaring Slam" }] },
		{ "name": "Rek'Sai", "cc": [{ "key": "W", "name": "Un-Burrow" }] },
		{ "name": "Rell", "cc": [{ "key": "W", "name": "Ferromancy: Crash Down" }, { "key": "E", "name": "Attract and Repel" }, { "key": "R", "name": "Magnet Storm" }] },
		{ "name": "Renata Glasc", "cc": [{ "key": "Q", "name": "Handshake" }, { "key": "R", "name": "Hostile Takeover" }] },
		{ "name": "Renekton", "cc": [{ "key": "W", "name": "Ruthless Predator" }] },
		{ "name": "Rengar", "cc": [{ "key": "E", "name": "Bola Strike" }] },
		{ "name": "Riven", "cc": [{ "key": "Q", "name": "Broken Wings" }, { "key": "W", "name": "Ki Burst" }] },
		{ "name": "Ryze", "cc": [{ "key": "W", "name": "Rune Prison" }] },
		{ "name": "Samira", "cc": [{ "key": "P", "name": "Daredevil Impulsive" }] },
		{ "name": "Sejuani", "cc": [{ "key": "Q", "name": "Arctic Assault" }, { "key": "E", "name": "Permafrost" }, { "key": "R", "name": "Glacial Prison" }] },
		{ "name": "Senna", "cc": [{ "key": "W", "name": "Last Embrace" }] },
		{ "name": "Seraphine", "cc": [{ "key": "E", "name": "Beat Drop" }, { "key": "R", "name": "Encore" }] },
		{ "name": "Sett", "cc": [{ "key": "E", "name": "Facebreaker" }, { "key": "R", "name": "The Show Stopper" }] },
		{ "name": "Shaco", "cc": [{ "key": "W", "name": "Jack in the Box" }, { "key": "R", "name": "Hallucinate" }] },
		{ "name": "Shen", "cc": [{ "key": "E", "name": "Shadow Dash" }] },
		{ "name": "Shyvana", "cc": [{ "key": "R", "name": "Dragon's Descent" }] },
		{ "name": "Singed", "cc": [{ "key": "W", "name": "Mega Adhesive" }, { "key": "E", "name": "Fling" }] },
		{ "name": "Sion", "cc": [{ "key": "Q", "name": "Decimating Smash" }, { "key": "R", "name": "Unstoppable Onslaught" }] },
		{ "name": "Skarner", "cc": [{ "key": "E", "name": "Fracture" }, { "key": "R", "name": "Impale" }] },
		{ "name": "Sona", "cc": [{ "key": "R", "name": "Crescendo" }] },
		{ "name": "Soraka", "cc": [{ "key": "E", "name": "Equinox" }] },
		{ "name": "Swain", "cc": [{ "key": "E", "name": "Nevermove" }] },
		{ "name": "Sylas", "cc": [{ "key": "E", "name": "Abduct" }] },
		{ "name": "Syndra", "cc": [{ "key": "E", "name": "Scatter the Weak" }] },
		{ "name": "Tahm Kench", "cc": [{ "key": "Q", "name": "Tongue Lash" }, { "key": "W", "name": "Abyssal Dive" }, { "key": "R", "name": "Devour" }] },
		{ "name": "Taliyah", "cc": [{ "key": "W", "name": "Seismic Shove" }, { "key": "E", "name": "Unraveled Earth" }, { "key": "R", "name": "Weaver's Wall" }] },
		{ "name": "Taric", "cc": [{ "key": "E", "name": "Dazzle" }] },
		{ "name": "Thresh", "cc": [{ "key": "Q", "name": "Death Sentence" }, { "key": "E", "name": "Flay" }] },
		{ "name": "Tristana", "cc": [{ "key": "R", "name": "Buster Shot" }] },
		{ "name": "Trundle", "cc": [{ "key": "E", "name": "Pillar of Ice" }] },
		{ "name": "Twisted Fate", "cc": [{ "key": "W", "name": "Pick A Card - Gold" }] },
		{ "name": "Udyr", "cc": [{ "key": "E", "name": "Blazing Stampede" }] },
		{ "name": "Urgot", "cc": [{ "key": "E", "name": "Disdain" }, { "key": "R", "name": "Fear Beyond Death" }] },
		{ "name": "Varus", "cc": [{ "key": "R", "name": "Chain of Corruption" }] },
		{ "name": "Vayne", "cc": [{ "key": "E", "name": "Condemn" }] },
		{ "name": "Veigar", "cc": [{ "key": "E", "name": "Event Horizon" }] },
		{ "name": "Vel'Koz", "cc": [{ "key": "E", "name": "Tectonic Disruption" }] },
		{ "name": "Vex", "cc": [{ "key": "P", "name": "Doom 'N Gloom" }] },
		{ "name": "Vi", "cc": [{ "key": "Q", "name": "Vault Breaker" }, { "key": "R", "name": "Cease and Desist" }] },
		{ "name": "Viego", "cc": [{ "key": "W", "name": "Spectral Maw" }] },
		{ "name": "Viktor", "cc": [{ "key": "W", "name": "Gravity Field" }] },
		{ "name": "Volibear", "cc": [{ "key": "Q", "name": "Thundering Smash" }] },
		{ "name": "Warwick", "cc": [{ "key": "E", "name": "Primal Howl" }, { "key": "R", "name": "Infinite Duress" }] },
		{ "name": "Wukong", "cc": [{ "key": "R", "name": "Cyclone" }] },
		{ "name": "Xayah", "cc": [{ "key": "E", "name": "Bladecaller" }] },
		{ "name": "Xerath", "cc": [{ "key": "E", "name": "Shocking Orb" }] },
		{ "name": "Xin Zhao", "cc": [{ "key": "Q", "name": "Three Talon Strike" }, { "key": "R", "name": "Crescent Guard" }] },
		{ "name": "Yasuo", "cc": [{ "key": "Q", "name": "Steel Tempest" }, { "key": "R", "name": "Last Breath" }] },
		{ "name": "Yone", "cc": [{ "key": "Q", "name": "Mortal Steel" }, { "key": "R", "name": "Fate Sealed" }] },
		{ "name": "Yorick", "cc": [{ "key": "W", "name": "Dark Procession" }] },
		{ "name": "Yuumi", "cc": [{ "key": "R", "name": "Final Chapter" }] },
		{ "name": "Zac", "cc": [{ "key": "Q", "name": "Stretching Strikes" }, { "key": "E", "name": "Elastic Slingshot" }, { "key": "R", "name": "Let's Bounce" }] },
		{ "name": "Ziggs", "cc": [{ "key": "W", "name": "Satchel Charge" }] },
		{ "name": "Zilean", "cc": [{ "key": "Q", "name": "Time Bomb" }] },
		{ "name": "Zoe", "cc": [{ "key": "W", "name": "Spell Thief" }, { "key": "E", "name": "Sleepy Trouble Bubble" }] },
		{ "name": "Zyra", "cc": [{ "key": "E", "name": "Grasping Roots" }, { "key": "R", "name": "Stranglethorns" }] }
	]
}