//world's most boring thing to do EVER.
//i need to figure out how to use the api. i wouldnt have to manually input each description >:(

export const champs = {
	"champions": [
		{ "name": "Aatrox", "lanes": ["Top"], "lolid": "0266" },
		{ "name": "Ahri", "lanes": ["Mid"], "lolid": "0103" },
		{ "name": "Akali", "lanes": ["Mid", "Top"], "lolid": "0084" },
		{ "name": "Akshan", "lanes": ["Mid", "Top"], "lolid": "0166" },
		{ "name": "Alistar", "lanes": ["Support"], "lolid": "0012" },
		{ "name": "Amumu", "lanes": ["Jungle", "Support"], "lolid": "0032" },
		{ "name": "Anivia", "lanes": ["Mid", "Support"], "lolid": "0034" },
		{ "name": "Annie", "lanes": ["Mid"], "lolid": "0001" },
		{ "name": "Aphelios", "lanes": ["ADC"], "lolid": "0523" },
		{ "name": "Ashe", "lanes": ["ADC", "Support"], "lolid": "0022" },
		{ "name": "Aurelion Sol", "lanes": ["Mid"], "lolid": "0136" },
		{ "name": "Azir", "lanes": ["Mid"], "lolid": "0268" },
		{ "name": "Bard", "lanes": ["Support"], "lolid": "0432" },
		{ "name": "Bel'Veth", "lanes": ["Jungle"], "lolid": "0200" },
		{ "name": "Blitzcrank", "lanes": ["Support", "Jungle"], "lolid": "0053" },
		{ "name": "Brand", "lanes": ["Support", "Mid"], "lolid": "0063" },
		{ "name": "Braum", "lanes": ["Support"], "lolid": "0201" },
		{ "name": "Caitlyn", "lanes": ["ADC"], "lolid": "0051" },
		{ "name": "Camille", "lanes": ["Top"], "lolid": "0164" },
		{ "name": "Cassiopeia", "lanes": ["Mid"], "lolid": "0069" },
		{ "name": "Cho'Gath", "lanes": ["Top", "Mid"], "lolid": "0031" },
		{ "name": "Corki", "lanes": ["Mid"], "lolid": "0042" },
		{ "name": "Darius", "lanes": ["Top"], "lolid": "0122" },
		{ "name": "Diana", "lanes": ["Jungle", "Mid"], "lolid": "0131" },
		{ "name": "Dr. Mundo", "lanes": ["Top", "Jungle"], "lolid": "0036" },
		{ "name": "Draven", "lanes": ["ADC"], "lolid": "0119" },
		{ "name": "Ekko", "lanes": ["Jungle", "Mid"], "lolid": "0245" },
		{ "name": "Elise", "lanes": ["Jungle"], "lolid": "0060" },
		{ "name": "Evelynn", "lanes": ["Jungle"], "lolid": "0028" },
		{ "name": "Ezreal", "lanes": ["ADC"], "lolid": "0081" },
		{ "name": "Fiddlesticks", "lanes": ["Jungle"], "lolid": "0009" },
		{ "name": "Fiora", "lanes": ["Top"], "lolid": "0114" },
		{ "name": "Fizz", "lanes": ["Mid"], "lolid": "0105" },
		{ "name": "Galio", "lanes": ["Mid", "Support"], "lolid": "0003" },
		{ "name": "Gangplank", "lanes": ["Mid", "Top"], "lolid": "0041" },
		{ "name": "Garen", "lanes": ["Top"], "lolid": "0086" },
		{ "name": "Gnar", "lanes": ["Top"], "lolid": "0150" },
		{ "name": "Gragas", "lanes": ["Top", "Jungle"], "lolid": "0079" },
		{ "name": "Graves", "lanes": ["Jungle"], "lolid": "0104" },
		{ "name": "Gwen", "lanes": ["Top", "Jungle"], "lolid": "0887" },
		{ "name": "Hecarim", "lanes": ["Jungle"], "lolid": "0120" },
		{ "name": "Heimerdinger", "lanes": ["Mid", "Top", "Support"], "lolid": "0074" },
		{ "name": "Illaoi", "lanes": ["Top"], "lolid": "0420" },
		{ "name": "Irelia", "lanes": ["Top", "Mid"], "lolid": "0039" },
		{ "name": "Ivern", "lanes": ["Jungle"], "lolid": "0427" },
		{ "name": "Janna", "lanes": ["Support"], "lolid": "0040" },
		{ "name": "Jarvan IV", "lanes": ["Jungle"], "lolid": "0059" },
		{ "name": "Jax", "lanes": ["Top", "Jungle"], "lolid": "0024" },
		{ "name": "Jayce", "lanes": ["Top", "Mid"], "lolid": "0126" },
		{ "name": "Jhin", "lanes": ["ADC"], "lolid": "0202" },
		{ "name": "Jinx", "lanes": ["ADC"], "lolid": "0222" },
		{ "name": "Kai'Sa", "lanes": ["ADC"], "lolid": "0145" },
		{ "name": "Kalista", "lanes": ["ADC"], "lolid": "0429" },
		{ "name": "Karma", "lanes": ["Support"], "lolid": "0043" },
		{ "name": "Karthus", "lanes": ["Jungle", "ADC"], "lolid": "0030" },
		{ "name": "Kassadin", "lanes": ["Mid"], "lolid": "0038" },
		{ "name": "Katarina", "lanes": ["Mid"], "lolid": "0055" },
		{ "name": "Kayle", "lanes": ["Top"], "lolid": "0010" },
		{ "name": "Kayn", "lanes": ["Jungle"], "lolid": "0141" },
		{ "name": "Kennen", "lanes": ["Top", "Mid"], "lolid": "0017" },
		{ "name": "Kha'Zix", "lanes": ["Jungle"], "lolid": "0121" },
		{ "name": "Kindred", "lanes": ["Jungle"], "lolid": "0203" },
		{ "name": "Kled", "lanes": ["Top"], "lolid": "0240" },
		{ "name": "Kog'Maw", "lanes": ["ADC"], "lolid": "0096" },
		{ "name": "K'Sante", "lanes": ["Top"], "lolid": "0897" },
		{ "name": "LeBlanc", "lanes": ["Mid"], "lolid": "0007" },
		{ "name": "Lee Sin", "lanes": ["Jungle"], "lolid": "0064" },
		{ "name": "Leona", "lanes": ["Support"], "lolid": "0089" },
		{ "name": "Lillia", "lanes": ["Top", "Jungle"], "lolid": "0876" },
		{ "name": "Lissandra", "lanes": ["Mid"], "lolid": "0127" },
		{ "name": "Lucian", "lanes": ["ADC", "Top", "Mid"], "lolid": "0236" },
		{ "name": "Lulu", "lanes": ["Support"], "lolid": "0117" },
		{ "name": "Lux", "lanes": ["Mid", "Support"], "lolid": "0099" },
		{ "name": "Malphite", "lanes": ["Top", "Mid"], "lolid": "0054" },
		{ "name": "Malzahar", "lanes": ["Mid"], "lolid": "0090" },
		{ "name": "Maokai", "lanes": ["Top", "Support", "Jungle"], "lolid": "0057" },
		{ "name": "Master Yi", "lanes": ["Jungle"], "lolid": "0011" },
		{ "name": "Miss Fortune", "lanes": ["ADC", "Support"], "lolid": "0021" },
		{ "name": "Mordekaiser", "lanes": ["Top", "Jungle"], "lolid": "0082" },
		{ "name": "Morgana", "lanes": ["Support"], "lolid": "0025" },
		{ "name": "Nami", "lanes": ["Support"], "lolid": "0267" },
		{ "name": "Nasus", "lanes": ["Top"], "lolid": "0075" },
		{ "name": "Nautilus", "lanes": ["Support"], "lolid": "0111" },
		{ "name": "Neeko", "lanes": ["Mid", "Top", "Support"], "lolid": "0518" },
		{ "name": "Nidalee", "lanes": ["Jungle"], "lolid": "0076" },
		{ "name": "Nilah", "lanes": ["ADC"], "lolid": "0895" },
		{ "name": "Nocturne", "lanes": ["Jungle", "Top", "Mid"], "lolid": "0056" },
		{ "name": "Nunu & Willump", "lanes": ["Jungle"], "lolid": "0020" },
		{ "name": "Olaf", "lanes": ["Jungle", "Top"], "lolid": "0002" },
		{ "name": "Orianna", "lanes": ["Mid"], "lolid": "0061" },
		{ "name": "Ornn", "lanes": ["Top"], "lolid": "0516" },
		{ "name": "Pantheon", "lanes": ["Mid", "Support", "Top"], "lolid": "0080" },
		{ "name": "Poppy", "lanes": ["Top", "Jungle", "Support"], "lolid": "0078" },
		{ "name": "Pyke", "lanes": ["Support", "Mid"], "lolid": "0555" },
		{ "name": "Qiyana", "lanes": ["Mid"], "lolid": "0246" },
		{ "name": "Quinn", "lanes": ["Top"], "lolid": "0133" },
		{ "name": "Rakan", "lanes": ["Support"], "lolid": "0497" },
		{ "name": "Rammus", "lanes": ["Jungle"], "lolid": "0033" },
		{ "name": "Rek'Sai", "lanes": ["Jungle"], "lolid": "0421" },
		{ "name": "Rell", "lanes": ["Support"], "lolid": "0526" },
		{ "name": "Renata Glasc", "lanes": ["Support"], "lolid": "0888" },
		{ "name": "Renekton", "lanes": ["Top", "Mid"], "lolid": "0058" },
		{ "name": "Rengar", "lanes": ["Top", "Jungle"], "lolid": "0107" },
		{ "name": "Riven", "lanes": ["Top"], "lolid": "0092" },
		{ "name": "Rumble", "lanes": ["Top", "Mid"], "lolid": "0068" },
		{ "name": "Ryze", "lanes": ["Mid", "Top"], "lolid": "0013" },
		{ "name": "Samira", "lanes": ["ADC"], "lolid": "0360" },
		{ "name": "Sejuani", "lanes": ["Jungle", "Top"], "lolid": "0113" },
		{ "name": "Senna", "lanes": ["Support"], "lolid": "0235" },
		{ "name": "Seraphine", "lanes": ["Mid", "Support", "ADC"], "lolid": "0147" },
		{ "name": "Sett", "lanes": ["Top"], "lolid": "0875" },
		{ "name": "Shaco", "lanes": ["Jungle"], "lolid": "0035" },
		{ "name": "Shen", "lanes": ["Top"], "lolid": "0875" },
		{ "name": "Shyvana", "lanes": ["Jungle", "Top"], "lolid": "0102" },
		{ "name": "Singed", "lanes": ["Top", "Mid"], "lolid": "0027" },
		{ "name": "Sion", "lanes": ["Top"], "lolid": "0014" },
		{ "name": "Sivir", "lanes": ["ADC"], "lolid": "0015" },
		{ "name": "Skarner", "lanes": ["Jungle", "Top"], "lolid": "0072" },
		{ "name": "Sona", "lanes": ["Support"], "lolid": "0037" },
		{ "name": "Soraka", "lanes": ["Support"], "lolid": "0016" },
		{ "name": "Swain", "lanes": ["Mid", "Support"], "lolid": "0050" },
		{ "name": "Sylas", "lanes": ["Mid"], "lolid": "0517" },
		{ "name": "Syndra", "lanes": ["Mid"], "lolid": "0134" },
		{ "name": "Tahm Kench", "lanes": ["Top", "Support"], "lolid": "0223" },
		{ "name": "Taliyah", "lanes": ["Jungle", "Mid"], "lolid": "0163" },
		{ "name": "Talon", "lanes": ["Mid", "Jungle"], "lolid": "0091" },
		{ "name": "Taric", "lanes": ["Support"], "lolid": "0044" },
		{ "name": "Teemo", "lanes": ["Top"], "lolid": "0017" },
		{ "name": "Thresh", "lanes": ["Support"], "lolid": "0412" },
		{ "name": "Tristana", "lanes": ["ADC"], "lolid": "0018" },
		{ "name": "Trundle", "lanes": ["Jungle", "Top"], "lolid": "0048" },
		{ "name": "Tryndamere", "lanes": ["Top", "Mid"], "lolid": "0023" },
		{ "name": "Twisted Fate", "lanes": ["Mid"], "lolid": "0004" },
		{ "name": "Twitch", "lanes": ["ADC", "Support", "Mid"], "lolid": "0029" },
		{ "name": "Udyr", "lanes": ["Jungle", "Top"], "lolid": "0077" },
		{ "name": "Urgot", "lanes": ["Top"], "lolid": "0006" },
		{ "name": "Varus", "lanes": ["ADC", "Mid"], "lolid": "0110" },
		{ "name": "Vayne", "lanes": ["ADC", "Top"], "lolid": "0067" },
		{ "name": "Veigar", "lanes": ["Mid", "ADC"], "lolid": "0045" },
		{ "name": "Vel'Koz", "lanes": ["Mid", "Support"], "lolid": "0161" },
		{ "name": "Vex", "lanes": ["Mid"], "lolid": "0711" },
		{ "name": "Vi", "lanes": ["Jungle"], "lolid": "0254" },
		{ "name": "Viego", "lanes": ["Jungle"], "lolid": "0234" },
		{ "name": "Viktor", "lanes": ["Mid"], "lolid": "0112" },
		{ "name": "Vladimir", "lanes": ["Mid", "Top"], "lolid": "0008" },
		{ "name": "Volibear", "lanes": ["Top", "Jungle"], "lolid": "0106" },
		{ "name": "Warwick", "lanes": ["Jungle", "Top"], "lolid": "0019" },
		{ "name": "Wukong", "lanes": ["Top", "Jungle"], "lolid": "0062" },
		{ "name": "Xayah", "lanes": ["ADC"], "lolid": "0498" },
		{ "name": "Xerath", "lanes": ["Mid", "Support"], "lolid": "0101" },
		{ "name": "Xin Zhao", "lanes": ["Jungle"], "lolid": "0005" },
		{ "name": "Yasuo", "lanes": ["Mid", "Top"], "lolid": "0157" },
		{ "name": "Yone", "lanes": ["Mid", "Top"], "lolid": "0777" },
		{ "name": "Yorick", "lanes": ["Top"], "lolid": "0083" },
		{ "name": "Yuumi", "lanes": ["Support"], "lolid": "0350" },
		{ "name": "Zac", "lanes": ["Jungle"], "lolid": "0154" },
		{ "name": "Zed", "lanes": ["Mid", "Jungle"], "lolid": "0238" },
		{ "name": "Zeri", "lanes": ["ADC"], "lolid": "0221" },
		{ "name": "Ziggs", "lanes": ["ADC", "Mid"], "lolid": "0115" },
		{ "name": "Zilean", "lanes": ["Mid", "Support"], "lolid": "0026" },
		{ "name": "Zoe", "lanes": ["Mid"], "lolid": "0142" },
		{ "name": "Zyra", "lanes": ["Support"], "lolid": "0143" }
	]
};

export const cc = {
	"champions": [
		{ "name": "Aatrox", "cc": [{"key": "Q", "name": "The Darkin Blade", "desc": "Aatrox performs a strike with his greatsword for each of the three casts, dealing <span class='ad'>physical damage</span> to enemies hit within an area. Enemies hit within a Sweetspot of the area take <img src='/ext/icons/inlines/crit.png' class='inlineicon'> <span class='crit'>60% bonus damage</span> and also <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'>knocked up</span> for 0.25 seconds. Each subsequent cast increases The Darkin Blade's damage by 25%."}, { "key": "W", "name": "Infernal Chains", "desc": "Aatrox sends a chain in the target direction that deals <span class='ad'>physical damage</span> to the first enemy hit, doubled against minions, and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowing</span> them by 25% for 1.5 seconds. If the tether is not broken by the end of its duration, the target is dealt the same <span class='ad'>physical damage</span> again and <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'>pulled</span> to the center of the area." }] },
		{ "name": "Ahri", "cc": [{ "key": "E", "name": "Charm", "desc": "Ahri blows forth a kiss in the target direction that deals <span class='ap'>magic damage</span> to the first enemy hit, <img src='/ext/icons/inlines/knockdown.png' class='inlineicon'> <span class='knockdown'>knocking them down</span> and <img src='/ext/icons/inlines/charm.png' class='inlineicon'> <span class='charm'>charming</span> and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowing</span> them by 65% for a duration." }] },
		{ "name": "Akali", "cc": [{ "key": "Q", "name": "Five Point Strike", "desc": "Akali unleashes kunais in a cone in the target direction, dealing <span class='ap'>magic damage</span> to enemies hit. Targets at maximum range are also <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowed</span> by 50% for 0.5 seconds." }] },
		{ "name": "Akshan", "cc": [] },
		{ "name": "Alistar", "cc": [{ "key": "Q", "name": "Pulverize", "desc": "Alistar smashes the ground, dealing <span class='ap'>magic damage</span> to nearby enemies and <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>stunning</span> and <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'>knocking them up</span> simultaneously for 1 second." }, { "key": "W", "name": "Headbutt", "desc": "Alistar dashes to the target enemy's location. If they are within 400 units upon arrival, he deals them <span class='ap'>magic damage</span> and <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'>knocks them back</span> 700 units over 0.5 seconds while also <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>stunning them</span> for 0.75 seconds." }, { "key": "E", "name": "Trample", "desc": "Alistar tramples the ground around him every 0.5 seconds over 5 seconds, becoming <span class='ghost'>ghosted</span> and dealing <span class='ap'>magic damage</span> to nearby enemies. Each time this damages at least one enemy champion, he generates a stack of <i>Trample</i> that lasts for the remaining duration, stacking up to 5 times. At 5 stacks, Alistar's next basic attack against a champion within 6 seconds is empowered to deal <span class='ap'>20 − 275 (based on level) bonus magic damage</span> and <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>stun the target</span> for 1 second. This will end Trample prematurely." }] },
		{ "name": "Amumu", "cc": [{ "key": "Q", "name": "Bandage Toss", "desc": "Amumu throws a bandage in the target direction that deals <span class='ap'>magic damage</span> to the first enemy hit, <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>stunning them</span> for 1 second and pulling him to them, during which they are revealed." }, { "key": "R", "name": "Curse of the Sad Mummy", "desc": "Amumu entangles nearby enemies in bandages, dealing <span class='ap'>magic damage</span> as well as <img src='/ext/icons/inlines/knockdown.png' class='inlineicon'> <span class='knockdown'>knocking down</span> and <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>stunning them</span> for 1.5 seconds." }] },
		{ "name": "Anivia", "cc": [{ "key": "Q", "name": "Flash Frost", "desc": "Anivia launches a chunk of ice in the target direction that deals <span class='ap'>magic damage</span> to enemies hit and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slows them</span> by 20% − 40% (based on Glacial Storm's Rank) for 3 seconds. On recast, Anivia shatters the ice, dealing <span class='ap'>magic damage</span> to nearby enemies and <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>stunning them</span> for a duration, as well as refreshing the <img src='/ext/icons/inlines/slow.png' class='inlineicon'> slow." }, {"key": "W", "name": "Crystallize", "desc": "Anivia summons a wall of ice at the target location perpendicular to her, <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'>knocking all units away</span> from it, though not through terrain. The wall lingers as impassable terrain for 5 seconds." }, { "key": "R", "name": "Glacial Storm", "desc": "Anivia calls forth a driving rain of ice and hail at the target location, dealing <span class='ap'>magic damage</span> every 0.5 seconds to enemies within and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowing them</span> for 1 second, refreshing every 0.5 seconds while they remain inside." }] },
		{ "name": "Annie", "cc": [{ "key": "P", "name": "Pyromania", "desc": "Annie generates a stack of <i>Pyromania</i> whenever she hits an enemy with  Disintegrate or casts her other abilities, stacking up to 4 times, at which she gains Energized. When she is Energized, Annie empowers her next cast of Disintegrate, Incinerate, or Summon: Tibbers to consume all <i>Pyromania</i> stacks to <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>stun enemies hit</span> for 1.25 / 1.5 / 1.75 (based on level) seconds." }] },
		{ "name": "Aphelios", "cc": [{ "key": "P", "name": "Gravitum", "desc": "Basic attacks with <i>Gravitum</i> <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slow enemies</span> by 30% for 3.5 seconds, decaying to 10% after 0.7 seconds." }, { "key": "Q", "name": "Gravitum - Active", "desc": "Aphelios expunges all enemies with <i>Gravitum's</i> <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slow debuff</span>, dealing <span class='ap'>magic damage</span> and <img src='/ext/icons/inlines/root.png' class='inlineicon'> <span class='root'>rooting them</span> for 1 second." }, { "key": "R", "name": "Moonlight Vigil", "desc": "Increases the initial <img src='/ext/icons/inlines/slow.png' class='inlineicon'> slow to 99% and empowers Binding Eclipse to <img src='/ext/icons/inlines/root.png' class='inlineicon'> <span class='root'>root targets</span> affected by the enhanced slow for 1.35 seconds." }] },
		{ "name": "Ashe", "cc": [{ "key": "P", "name": "Frost Shot", "desc": "Ashe's basic attacks and ability hits apply Frost to enemies, which <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slows them</span> by 20% − 30% (based on level) for 2 seconds. Basic attacks against enemies with Frost are modified to deal 110% damage." }, { "key": "W", "name": "Volley", "desc": "Ashe shoots a volley of arrows in a cone in the target direction, each dealing <span class='ad'>physical damage</span> to the first enemy hit, and applying <i>Critical Slow</i> to enemy champions hit." }, { "key": "R", "name": "Enchanted Crystal Arrow", "desc": "Ashe fires a massive arrow of ice in the target direction, granting sight of the area it flies through each for 1 second. The arrow shatters upon hitting an enemy champion, dealing them <span class='ap'>magic damage</span>, <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>stunning them</span> for 1 − 3.5 (based on distance traveled) seconds, and granting sight of the area around them for 1 second." }] },
		{ "name": "Aurelion Sol", "cc": [{ "key": "Q", "name": "Starsurge", "desc": "Aurelion Sol fires a star in the target direction that expands as long as it remains within the Outer Limit, granting him <img src='/ext/icons/inlines/speed.png' class='inlineicon'> <span class='speed'>20% bonus movement speed</span> while active. If he moves faster than the star, the speed of the star will increase to stay within the Outer Limit. Starsurge can be recast after 0.25 seconds while the star is active, and does so automatically when the star travels beyond the Outer Limit. On recast, Aurelion Sol detonates the star, dealing <span class='ap'>magic damage</span> to nearby enemies and <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>stunning them</span> for a duration, which is increased by 0% − 300% (based on time traveled)." }, { "key": "R", "name": "Voice of Light", "desc": "Aurelion Sol exhales a wave of star fire in the target direction, granting sight of the area for 2 seconds from the start of the cast time, dealing <span class='ap'>magic damage</span> to enemies within its path, <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowing them</span> for 2 seconds and, if they are within the Outer Limit, <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>stunning them</span> for 0.125 seconds and <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'>knocking them back</span> to it, though not through terrain." }] },
		{ "name": "Azir", "cc": [{ "key": "Q", "name": "Conquering Sands", "desc": "Azir orders all Sand Soldiers to dash toward the target location, dealing <span class='ap'>magic damage</span> to all enemies they pass through and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowing them</span> by 25% for 1 second." }, { "key": "R", "name": "Emperor's Divide", "desc": "Azir calls forth a phalanx of soldiers from 175 units behind him, catching enemies from up to 325 units behind him and charging forward 575 units in the target direction. Enemies impacted by the charge are dealt <span class='ap'>magic damage</span> and <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'>knocked away</span over 1 second to a line 650 units in front of Azir." }] },
		{ "name": "Bard", "cc": [{ "key": "Q", "name": "Cosmic Binding", "desc": "Bard fires an energy bolt in the target direction that deals <span class='ap'>magic damage</span> to the first enemy hit and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slows them</span> by 60% for a duration. After Cosmic Binding hits an enemy, the bolt continues behind them for 300 units. If the bolt hits terrain or a second enemy, it <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>stuns both targets</span> for the same duration, dealing the <span class='ap'>same damage</span> to the secondary target." }, { "key": "R", "name": "Tempered Fate", "desc": "Bard sends magical energy arcing to the target location, granting sight of the area during travel. Upon impact, it puts all units within into <img src='/ext/icons/inlines/stasis.png' class='inlineicon'> <span class='stasis'>stasis</span> for 2.5 seconds, as well as <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>stunning</span> all enemy champions, minions, and turrets struck for the same duration. Enemies hit are revealed for the duration." }] },
		{ "name": "Bel'Veth", "cc": [{ "key": "W", "name": "Above and Below", "desc": "Bel'Veth slams her tail down in the target direction that deals <span class='ap'>magic damage</span> to enemies hit, <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'>knocks them up</span> for 0.75 seconds, and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slows them</span> by 50% for a duration." }] },
		{ "name": "Blitzcrank", "cc": [{ "key": "Q", "name": "Rocket Grab", "desc": "Blitzcrank fires their right hand in the target direction that catches the first enemy hit, dealing them <span class='ap'>magic damage</span>, <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>stunning them</span> for 0.65 seconds, and <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'>pulling them towards</span> Blitzcrank, during which they are revealed." }, { "key": "E", "name": "Power Fist", "desc": "Blitzcrank empowers their next basic attack within 5 seconds to have an uncancellable windup, deal <span class='ad'>75% AD </span><span class='ap'>(+ 25% AP)</span> bonus <span class='ad'>physical damage</span>, increased to <span class='ad'>250% AD</span> <span class='ap'>(+ 150% AP)</span> against non-champions, and <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'>knock up the target</span> for 1 second. This damage is affected by critical strike modifiers." }, { "key": "R", "name": "Static Field", "desc": "Blitzcrank detonates a static field, completely destroying damage-mitigating shields of nearby enemies before dealing them <span class='ap'>magic damage</span> and <img src='/ext/icons/inlines/silence.png' class='inlineicon'> <span class='silence'>silencing them</span> for 0.5 seconds." }] },
		{ "name": "Brand", "cc": [{ "key": "Q", "name": "Sear", "desc": "Brand's abilities apply a stack of Ablaze to enemies hit for 4 seconds. Brand launches a fireball in the target direction that deals <span class='ap'>magic damage</span> to the first enemy hit. Ablaze bonus: The target is <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>stunned</span> for 1.5 seconds." }] },
		{ "name": "Braum", "cc": [{ "key": "P", "name": "Concussive Blows", "desc": "Braum's basic attacks and Winter's Bite Winter's Bite each apply a stack of Concussive Blows to their target for 4 seconds, refreshing on subsequent applications and stacking up to 4 times. Once the first stack has been applied, any allied champion's basic attack applies an additional stack to the target on-hit. The fourth stack against a target consumes them all to deal 26 − 196 (based on level) <span class='ap'>magic damage</span> and <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>stun them</span> for 1.25 − 1.75 (based on level) seconds." }, { "key": "Q", "name": "Winter's Bite", "desc": "Braum propels ice from his shield in the target direction, dealing <span class='ap'>magic damage</span> to the first enemy hit and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowing them</span> by 70% decaying over 2 seconds." }, { "key": "R", "name": "Glacial Fissure", "desc": "Braum leaps into the air and slams his shield into the ground, creating a fissure that travels forth in the target direction, dealing <span class='ap'>magic damage</span> to enemies within its path as well as those around Braum. The first target hit is <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'>knocked up</span> for at least 0.3 seconds, increased if they are further away from Braum. All other enemies hit are <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'>knocked up</span> for 0.3 seconds. A field of ice is created along the fissure's path, lasting for 4 seconds and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowing enemies</span> within the area every 0.25 seconds. The field disappears after the duration ends in the same order and speed it was created with." }] },
		{ "name": "Caitlyn", "cc": [{ "key": "W", "name": "Yordle Snap Trap", "desc": "The next enemy champion that springs the trap is <img src='/ext/icons/inlines/root.png' class='inlineicon'> <span class='root'>rooted</span> for 1.5 seconds, revealed for 3 seconds, takes additional damage from Headshot, and becomes immune to further Yordle Snap Traps for 3 seconds." }, { "key": "E", "name": "90 Caliber Net", "desc": "Caitlyn fires a net in the target direction and recoils 390 units in the opposite direction. The net deals <span class='ap'>magic damage</span> to the first enemy hit and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slows them</span> by 50% for 1 second." }] },
		{ "name": "Camille", "cc": [{ "key": "W", "name": "Tactical Sweep", "desc": "Enemies hit by the outer half of the cone take additional <span class='ad'>physical damage</span>, capped at 300 damage against monsters, and are <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowed</span> by 80% decaying over 2 seconds. Camille is healed for 100% of this additional damage post-mitigation against enemy champions in the outer half." }, { "key": "E", "name": "Hookshot", "desc": "Camille stops prematurely upon colliding with an enemy champion, <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'>knocking back</span> all nearby enemy champions, though not through terrain, as well as <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>stunning them</span> for 0.75 seconds, while also gaining bonus attack speed for 5 seconds." }, { "key": "R", "name": "The Hextech Ultimatum", "desc": "Upon landing on the target, she becomes targetable again and creates a hexagonal zone around her current location for a duration, <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'>knocking away</span> all other nearby enemies on impact, though not through terrain." }] },
		{ "name": "Cassiopeia", "cc": [{ "key": "W", "name": "Miasma", "desc": "Enemies within the clouds are poisoned to take <span class='ap'>magic damage</span> every second and become <img src='/ext/icons/inlines/ground.png' class='inlineicon'> <span class='ground'>grounded</span> and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowed</span> by an amount that decays over the area's duration." }, { "key": "R", "name": "Petrifying Gaze", "desc": "Cassiopeia blasts enemies in a cone in the target direction, dealing <span class='ap'>magic damage</span> to enemies struck within and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowing them</span> by 40% for 2 seconds. Enemies with their facing direction towards her are instead <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>stunned</span> for the same duration." }] },
		{ "name": "Cho'Gath", "cc": [{ "key": "Q", "name": "Rupture", "desc": "Cho'Gath ruptures the target location after a 0.627 seconds-second delay, granting sight of the area before dealing <span class='ap'>magic damage</span> to enemies within and <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'>knocking them up</span> for 1 second, and afterwards <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowing them</span> by 60% for 1.5 seconds." }, { "key": "W", "name": "Feral Scream", "desc": "Cho'Gath roars in a cone in the target direction, dealing <span class='ap'>magic damage</span> to enemies hit. Enemy champions and Rift Scuttlers hit are also <img src='/ext/icons/inlines/silence.png' class='inlineicon'> <span class='silence'>silenced</span> for a duration." }, { "key": "E", "name": "Vorpal Spikes", "desc": "Cho'Gath empowers its next 3 basic attacks within 6 seconds to gain 50 bonus range and launch a blast of spikes on-attack in the target's direction. Enemies struck are dealt <span class='ap'>magic damage</span> and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowed</span> by an amount that decays over 1.5 seconds. The damage based on the target's health ratio is capped at 60 against minions and monsters." }] },
		{ "name": "Corki", "cc": [{ "key": "W", "name": "Special Delivery", "desc": "Corki dashes with displacement immunity to the target location, <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'>knocking aside</span> all enemies in his path 500 units and leaving behind a trail of fire for 5 seconds, which grants sight of the area for its duration and for 3 seconds afterwards." }] },
		{ "name": "Darius", "cc": [{ "key": "W", "name": "Crippling Strike", "desc": "Darius empowers his next basic attack within 4 seconds to have an uncancellable windup, gain 25 bonus range, deal modified <span class='ad'>physical damage</span> and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slow the target</span> by 90% for 1 second." }, { "key": "E", "name": "Apprehend", "desc": "Darius sweeps his axe in a cone in the target direction, briefly granting Sight icon.png sight of the area and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowing enemies</span> hit by 40% for 2 seconds while <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'>pulling them towards</span> him. Upon arrival, they rebound 150 units off of him, remaining <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'>airborne</span> for 1 second." }] },
		{ "name": "Diana", "cc": [{ "key": "R", "name": "Moonfall", "desc": "Diana <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'>pulls in</span> all nearby enemies, during which they are revealed, then <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slows them</span> for 2 seconds." }] },
		{ "name": "Dr. Mundo", "cc": [{ "key": "Q", "name": "Infected Bonesaw", "desc": "Dr. Mundo throws an infected bonesaw in the target direction that deals <span class='ap'>magic damage</span> to the first enemy hit and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slows them</span> by 40% for 2 seconds." }] },
		{ "name": "Draven", "cc": [{ "key": "E", "name": "Stand Aside", "desc": "Draven throws a fan of axes in a line in the target direction, dealing <span class='ad'>physical damage</span> to enemies hit, <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'>knocking them aside</span>, though not through terrain, and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowing them</span> for 2 seconds." }] },
		{ "name": "Ekko", "cc": [{ "key": "Q", "name": "Timewinder", "desc": "Ekko throws a temporal grenade in the target direction that deals <span class='ap'>magic damage</span> to enemies hit. At 700 units or upon hitting an enemy champion, the grenade slows down for 1.75 seconds to gradually expand into a Temporal Sickness field that <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slows nearby enemies</span>, travelling for another 190 units." }, { "key": "W", "name": "Parallel Convergence", "desc": "Ekko calls upon an afterimage that bats a device to the target location, granting sight of the area for 2.5 seconds after 2 seconds. After 3 seconds, the device will expand into a field for 1.5 seconds, <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowing enemies</span> within by 40%. If Ekko enters the field, it detonates to grant him a shield for 2 seconds and <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>stun enemies within</span> for 2.25 seconds." }] },
		{ "name": "Elise", "cc": [{ "key": "E", "name": "Cocoon", "desc": "Elise fires a web in the target direction, <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>stunning the first enemy hit</span> for a few seconds, during which they are also revealed." }] },
		{ "name": "Evelynn", "cc": [{ "key": "W", "name": "Allure", "desc": "Evelynn curses the target enemy champion or monster for 5 seconds. Evelynn's next basic attack or ability against the accursed target expunges them, <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowing them</span> by 65% for 0.75 seconds. Expunging a target will refund Allure's mana cost. If the target is cursed for at least 2.5 seconds, the expunge also <img src='/ext/icons/inlines/charm.png' class='inlineicon'> <span class='charm'>charms them</span> for a few seconds and the duration of the <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slow</span> is increased to last for this time, as well as applying additional effects based on the target type." }] },
		{ "name": "Ezreal", "cc": [] },
		{ "name": "Fiddlesticks", "cc": [{ "key": "Q", "name": "Terrify", "desc": "While Fiddlesticks has been out of combat for at least 2.5 seconds and is not visible to the enemy team, or is pretending to be an Effigy, its next damaging ability will additionally <img src='/ext/icons/inlines/fear.png' class='inlineicon'> <span class='fear'>fear targets hit</span> for a duration. Fiddlesticks's Terrify launches a crow at the target enemy that deals <span class='ap'>magic damage</span> and <img src='/ext/icons/inlines/fear.png' class='inlineicon'> <span class='fear'>fears them</span> for a duration." }, { "key": "E", "name": "Reap", "desc": "Fiddlesticks slashes the target location with its scythe, dealing <span class='ap'>magic damage</span> to enemies within the area and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowing them</span> for 1.25 seconds." }] },
		{ "name": "Fiora", "cc": [{ "key": "W", "name": "Riposte", "desc": "Fiora enters a defensive stance for 0.75 seconds, becoming unable to act, preventing all incoming non-turret damage, and gaining debuff immunity and crowd control immunity. Additionally, Fiora poises to strike, after which she sends a shock with her sword in a line in the target direction, dealing <span class='ap'>magic damage</span> to all enemies hit until colliding with an enemy champion. The enemy champion struck is also <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowed</span> and <img src='/ext/icons/inlines/asreduce.png' class='inlineicon'> <span class='asreduce'>has their attack speed reduced by 50%</span> for 2 seconds. If Riposte negates at least one hostile <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>immobilizing effect</span>, Fiora <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>stuns the target</span> for the same duration instead." }, { "key": "E", "name": "Bladework", "desc": "Fiora empowers her next two basic attacks on-attack within 4 seconds to gain 25 bonus range and bonus attack speed. The first attack <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slows the target</span> by 30% for 1 second." }] },
		{ "name": "Fizz", "cc": [{ "key": "R", "name": "Chum the Waters", "desc": "Fizz throws down a lure at the target location that attracts a shark, granting sight of the area before it emerges to chomp at the lure after 2 seconds, dealing <span class='ap'>magic damage</span> to nearby enemies, <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'><span class='knockup'>knocking them back</span></span>, though not through terrain, and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowing them</span> for 2 seconds." }] },
		{ "name": "Galio", "cc": [{ "key": "W", "name": "Shield of Durand", "desc": "Galio charges for up to 3 seconds, <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowing himself</span> by 15%, and gaining <span class='ap'>magic damage</span> reduction and half of that amount as <span class='ad'>physical damage</span> reduction; charging increases Shield of Durand's radius, damage and <img src='/ext/icons/inlines/taunt.png' class='inlineicon'> <span class='taunt'>taunt</span> over the first 2 seconds of the channel." }, { "key": "E", "name": "Justice Punch", "desc": "During the cast time, Galio steps backwards in the opposite direction. He then dashes to the target location until he hits an enemy champion or terrain. Galio deals <span class='ap'>magic damage</span> to enemies he passes through, reduced by 50% against non-champions, and <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'>knocks them up</span> for 0.75 seconds as well as reveals them for the same duration." }, { "key": "R", "name": "Hero's Entrance", "desc": "After channeling for 1.25 seconds, he gains crowd control immunity for the remaining duration, becomes untargetable, and leaps into the air for 0.85 seconds before dashing to his destination over 0.25 seconds. Afterwards, he lands and becomes targetable again, dealing <span class='ap'>magic damage</span> to all nearby enemies upon impact, <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'><span class='knockup'>knocking them back</span></span> 100 units over 0.75 seconds, and remaining in place for 0.4 seconds." }] },
		{ "name": "Gangplank", "cc": [{ "key": "E", "name": "Powder Keg", "desc": "Enemies caught in a keg's explosion are <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowed</span> for 2 seconds, and are dealt the triggering attack's damage, dealing bonus <span class='ad'>physical damage</span> against champions. Each enemy can only be hit once per chain and the damage dealt ignores 40% of the target's armor." }, { "key": "R", "name": "Cannon Barrage", "desc": "Gangplank shoots a flare into the air, signaling his ship off-shore to fire upon the target location for 8 seconds, calling down 12 waves of cannonballs in clusters of 3 every 2 seconds, and granting sight of the area for the duration. Each wave deals <span class='ap'>magic damage</span> to all enemies within the area and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slows them</span> by 30% for 0.5 seconds." }] },
		{ "name": "Garen", "cc": [{ "key": "Q", "name": "Decisive Strike", "desc": "Garen empowers his next basic attack within 4.5 seconds to have an uncancellable windup, lunge at the target, deal bonus <span class='ad'>physical damage</span>, and <img src='/ext/icons/inlines/silence.png' class='inlineicon'> <span class='silence'>silence the target</span> for 1.5 seconds."}] },
		{ "name": "Gnar", "cc": [{ "key": "Q", "name": "Boomerang Throw / Boulder Toss", "desc": "Mini Gnar throws a boomerang in a line in the target direction that deals <span class='ad'>physical damage</span> to enemies in its path and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slows them</span> for 2 seconds. Mega Gnar throws a boulder in the target direction that stops upon hitting an enemy, dealing <span class='ad'>physical damage</span> to nearby enemies upon impact and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowing them</span> for 2 seconds. The boulder then remains on the ground for 6 seconds." }, { "key": "W", "name": "Wallop", "desc": "Mega Gnar slams his arm down in the target direction, dealing <span class='ad'>physical damage</span> to all enemies struck within the area and <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>stunning them</span> for 1.25 seconds." }, { "key": "R", "name": "GNAR!", "desc": "Mega Gnar thrusts in the target direction, <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'>knocking away</span> nearby enemies up to 590 units in that direction, though not through terrain, and afterwards dealing them <span class='ad'>physical damage</span>, as well as <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowing them</span> by 45% after a 0.4-second delay for a duration. Enemies that collide with terrain take 50% increased damage instantly and are <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>stunned</span> instead of <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowed</span>." }] },
		{ "name": "Gragas", "cc": [{ "key": "Q", "name": "Barrel Roll", "desc": "Gragas rolls a cask to the target location, remaining there for 4 seconds, granting sight of the area, and fermenting over 2 seconds to increase its damage and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slow effectiveness</span>, up to a maximum of 150%. Barrel Roll can be recast at any time within its duration after the cask has fully travelled, and does so automatically after its duration ends. On recast, Gragas detonates the cask, dealing <span class='ap'>magic damage</span> to nearby enemies, reduced by 30% against minions, and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowing them</span> for 2 seconds." }, { "key": "E", "name": "Body Slam", "desc": "Gragas charges in the target direction and stops upon colliding with an enemy, dealing <span class='ap'>magic damage</span> to all nearby enemies, <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'><span class='knockup'>knocking them back</span></span>, though not through terrain, and <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>stunning them</span> for 1 second." }, { "key": "R", "name": "Explosive Cask", "desc": "Gragas hurls a cask that travels to the target location over 0.55 seconds, exploding on impact to deal <span class='ap'>magic damage</span> to all enemies within the area and <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'>knock them back</span> 900 units, though not through terrain, from the epicenter of the explosion, as well as granting sight of the area for 1 second." }] },
		{ "name": "Graves", "cc": [{ "key": "W", "name": "Smoke Screen", "desc": "Graves fires a smoke canister at the target location that upon impact deals <span class='ap'>magic damage</span> to enemies within the area and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slows them</span> by 50% for 0.5 seconds. The canister creates a cloud of smoke for 4 seconds that applies <img src='/ext/icons/inlines/nearsight.png' class='inlineicon'> <span class='nearsight'>nearsight</span> of outside the area to all enemies within every 0.25 seconds, reducing their sight radius relative to the center." }] },
		{ "name": "Gwen", "cc": [{ "key": "R", "name": "Needlework", "desc": "Gwen launches needle(s) in the target direction that deals <span class='ap'>magic damage</span> to enemies hit and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slows them</span> for 1.5 seconds." }] },
		{ "name": "Hecarim", "cc": [{ "key": "E", "name": "Devastating Charge", "desc": "Hecarim empowers his next basic attack to gain 50 − 250 (based on distance traveled) bonus range and cause him to dash in the target's direction, revealing them for 1 second. If the target remains nearby during the dash, the ghosting and bonus movement speed ends prematurely and Hecarim <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'>knocks them back</span> 150 − 350 (based on distance traveled) units, though not through terrain, <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>stuns them</span> for 0.25 seconds, and deals them modified <span class='ad'>physical damage</span>, increased by 0% − 100% (based on distance traveled)." }, { "key": "R", "name": "Onslaught of Shadows", "desc": "Hecarim dashes with displacement immunity to the target location and summons 5 spectral riders in an arrow formation that charge alongside him in the target direction, dealing <span class='ap'>magic damage</span> to all enemies in their path and revealing them for 2.5 seconds. Upon arrival, he <img src='/ext/icons/inlines/fear.png' class='inlineicon'> <span class='fear'>fears nearby enemies</span> for 0.75 − 1.5 (based on distance traveled) seconds and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slows them</span>, ramping to 99% over the duration." }] },
		{ "name": "Heimerdinger", "cc": [{ "key": "E", "name": "CH-2 Electron Storm Grenade", "desc": "Heimerdinger hurls a grenade at the target location that detonates upon impact, dealing <span class='ap'>magic damage</span> to nearby enemies and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowing them</span> by 35% for 2 seconds. Enemies hit at the center of the grenade's impact are also <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>stunned</span> for 1.5 seconds." }] },
		{ "name": "Illaoi", "cc": [{ "key": "E", "name": "Test of Spirit", "desc": "Illaoi launches a tendril in the target direction that stops at the first enemy hit, pulling their Spirit out in front of Illaoi over 0.75 seconds if they're a champion. The target is tethered to the Spirit for 7 seconds, revealing them in addition to granting sight of the area around them while the tether remains. When the Spirit is killed or the target leaves tether range, the tether is severed, marking the target as a Vessel for 10 seconds and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowing them</span> by 80% for 1.5 seconds once the tether returns back to them." }] },
		{ "name": "Irelia", "cc": [{ "key": "E", "name": "Flawless Duet", "desc": "Irelia sends a blade to the target location for 3.5 seconds. Flawless Duet can be recast after 0.15 seconds while the blade is active, and does so automatically at the end of its duration, though not if she is unable to cast abilities. Once both blades have been placed, they fly toward each other regardless of distance and converge over 0.25 seconds, afterwards dealing <span class='ap'>magic damage</span> to all enemies within a line between them and <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>stunning them</span> for 0.75 seconds, during which they are revealed." }, { "key": "R", "name": "Vanguard's Edge", "desc": "Irelia launches a barrage of blades in the target direction, expanding outward upon hitting an enemy champion, dealing <span class='ap'>magic damage</span> to all enemies hit and revealing them for 1 second. After expanding, the blades drop on the ground, knocking all enemy units away from them, and forming a spade-shaped perimeter around the enemy champion hit for 2.5 seconds that grants sight of its surroundings. Enemies that pass through the blades for the first time are dealt the same magic damage and are <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowed</span> by 90% for 1.5 seconds." }] },
		{ "name": "Ivern", "cc": [{ "key": "Q", "name": "Rootcaller", "desc": "Ivern throws a vine in the target direction, dealing <span class='ap'>magic damage</span> to the first enemy hit and <img src='/ext/icons/inlines/root.png' class='inlineicon'> <span class='root'>rooting them</span> for a duration, during which they are also revealed." }, { "key": "E", "name": "Triggerseed", "desc": "Ivern places a seed on the target allied champion, Daisy, or himself, granting the target a shield for 2 seconds. After 2 seconds, the seed explodes to deal <span class='ap'>magic damage</span> to nearby enemies and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slow them</span> for 2 seconds." }, { "key": "R", "name": "Daisy!", "desc": "Daisy's basic attacks apply stacks of Daisy Smash!, resetting whenever she attacks a new target. Against a target with 2 stacks, Daisy's next basic attack gains 50 bonus attack range and is empowered to charge up for 0.625 seconds to send a shockwave in a line toward the target that deals 100% of her AD (+ 20% AP) <span class='ap'>magic damage</span> to enemies hit and <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>stuns</span>, and <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'>knocks them up</span> for 1 second. Daisy Smash! cannot occur again for 3 seconds." }] },
		{ "name": "Janna", "cc": [{ "key": "Q", "name": "Howling Gale", "desc": "Janna summons a whirlwind at her current location that charges up over 3 seconds, increasing its range, speed, damage, and <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'>knock up duration</span> every second over the duration. Howling Gale's direction is determined by this cast. On recast, Janna launches the whirlwind in the direction she targeted over 1.25 seconds, dealing <span class='ap'>magic damage</span> to enemies hit and <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'>knocking them up</span> for 0.5 − 1.25 seconds." }, { "key": "W", "name": "Zephyr", "desc": "Janna sends an air elemental at the target enemy that deals <span class='ap'>magic damage</span> and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slows them</span> for 3 seconds." }, { "key": "R", "name": "Monsoon", "desc": "Janna unleashes a blast that <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'>knocks back all nearby enemies</span>, though not through terrain." }] },
		{ "name": "Jarvan IV", "cc": [{ "key": "Q", "name": "Dragon Strike", "desc": "Jarvan IV extends his lance in the target direction, dealing <span class='ad'>physical damage</span> to enemies hit and inflicting them with armor reduction for 3 seconds. If the lance connects with a deployed <i>Demacian Standard</i>, Jarvan IV dashes to its location, <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'>knocking up nearby enemies</span> around him and along his path for 0.75 seconds." }, { "key": "W", "name": "Golden Aegis", "desc": "Jarvan IV <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slows all nearby enemies</span> for 2 seconds." }] },
		{ "name": "Jax", "cc": [{ "key": "E", "name": "Counter Strike", "desc": "On recast, Jax deals <span class='ad'>physical damage</span> to nearby enemies, increased by 20% for each attack dodged, up to a 100% increase, and <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>stuns them</span> for 1 second." }] },
		{ "name": "Jayce", "cc": [{ "key": "Q", "name": "To the Skies!", "desc": "Jayce leaps to the target enemy's location. Upon arrival, he deals <span class='ad'>physical damage</span> to all enemies within an area and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slows them</span> for 2 seconds." }, { "key": "E", "name": "Thundering Blow", "desc": "Jayce swings his hammer at the target enemy, dealing <span class='ap'>magic damage</span>, capped against monsters, while also <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'>displacing them</span> to a location 500 units in front of him." }] },
		{ "name": "Jhin", "cc": [{ "key": "W", "name": "Deadly Flourish", "desc": "Passively, Deadly Flourish marks enemy champions that trigger a Lotus Trap to bloom or are damaged by Jhin or allied champions. When activated, Deadly Flourish fires a shot in the target direction that deals <span class='ad'>physical damage</span> to all enemies in a line until colliding with an enemy champion, reduced by 25% against minions. Hitting a marked champion <img src='/ext/icons/inlines/root.png' class='inlineicon'> <span class='root'>roots them</span> for a duration and grants Jhin bonus movement speed." }, { "key": "E", "name": "Captive Audience", "desc": "Blooming Lotus Traps <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slow enemies</span> within the area by 35% for 2 seconds before exploding, dealing <span class='ap'>magic damage</span> to enemies." }, { "key": "R", "name": "Curtain Call", "desc": "On recast, Jhin fires a round in the target direction that grants sight around its trajectory for 0.5 seconds and deals <span class='ad'>physical damage</span> to enemies hit, increased based on target's missing health. The bullet stops upon hitting an enemy champion, <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowing them</span> by 80% for 0.5 seconds and revealing them for 2 seconds. Each cast has a static cooldown of 1 second." }] },
		{ "name": "Jinx", "cc": [{ "key": "W", "name": "Zap!", "desc": "Jinx fires a shock blast in the target direction that deals <span class='ad'>physical damage</span> to the first enemy it hits and reveals and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slows them</span> for 2 seconds." }, { "key": "E", "name": "Flame Chompers!", "desc": "Jinx tosses out 3 Chompers that explode after 5 seconds to deal <span class='ap'>magic damage</span> to nearby enemies. Each Chomper explodes on contact with an enemy champion, <img src='/ext/icons/inlines/knockdown.png' class='inlineicon'> <span class='knockdown'>knocking them down</span> and <img src='/ext/icons/inlines/root.png' class='inlineicon'> <span class='root'>rooting them</span> for 1.5 seconds." }] },
		{ "name": "Kai'Sa", "cc": [] },
		{ "name": "Kalista", "cc": [{"key": "E", "name": "Rend", "desc": "Kalista rips all lodged spears from nearby enemies, consuming all of their stacks to deal them <span class='ad'>physical damage</span> and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slow them</span> for 2 seconds."}, { "key": "R", "name": "Fate's Call", "desc": "Kalista invokes her tether to retrieve her Oathsworn and hold them for 4 seconds, pulling them to her over 1 second and cleansing them from all <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>crowd control</span>, as well as rendering them invulnerable and untargetable for the duration. While held, the Oathsworn is vanished and may dash with displacement immunity to end Fate's Call's effects and reappear at the target location; after the duration, they will automatically do so at maximum range from Kalista's facing direction. The Oathsworn stops upon colliding with an enemy champion, <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'>knocking up all nearby enemies</span> for a duration and landing to their basic attack range from the target collided with." }] },
		{ "name": "Karma", "cc": [{ "key": "Q", "name": "Inner Flame", "desc": "Karma fires a bolt in the target direction that explodes on the first enemy hit, dealing <span class='ap'>magic damage</span> to nearby enemies and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowing them</span> by 35% for 1.5 seconds. When enhanced by her ultimate, Inner Flame deals increased damage, and fires a larger bolt that also explodes at maximum range. The explosion creates a field for 1.5 seconds that <img src='/ext/icons/inlines/slow.png' class='inlineicon'> slows enemies within by 50%, which then ruptures to deal <span class='ap'>magic damage</span>." }, { "key": "E", "name": "Focused Resolve", "desc": "Karma deals <span class='ap'>magic damage</span> to the target enemy champion or monster and forms a tether between her and them for 2 seconds, during which they are revealed. If the tether is not broken by the end of its duration, the target is dealt the same magic damage again and is <img src='/ext/icons/inlines/root.png' class='inlineicon'> <span class='root'>rooted</span> for a duration, during which they are revealed." }] },
		{ "name": "Karthus", "cc": [{ "key": "W", "name": "Wall of Pain", "desc": "Karthus erects a wall of pain that lasts 5 seconds, granting sight around its pillars and center. Enemies that touch the wall are inflicted with 15% magic resistance reduction and become <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowed</span> for 4 seconds, decaying over the duration. Enemies can be affected by Wall of Pain only once per cast." }] },
		{ "name": "Kassadin", "cc": [{ "key": "E", "name": "Force Pulse", "desc": "Kassadin emits a pulse of void energy in a cone in the target direction that deals <span class='ap'>magic damage</span> to enemies hit and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slows them</span> for 1 second." }] },
		{ "name": "Katarina", "cc": [] },
		{ "name": "Kayle", "cc": [{ "key": "Q", "name": "Radiant Blast", "desc": "Kayle conjures a portal, from which a celestial sword launches forward. The sword expands upon hitting an enemy, targets struck in the area are dealt <span class='ap'>magic damage</span> and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowed</span> for 2 seconds." }] },
		{ "name": "Kayn", "cc": [{ "key": "W", "name": "Blade's Reach", "desc": "Kayn swings his scythe in the target direction, dealing <span class='ad'>physical damage</span> to enemies hit and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowing them</span> by 90% decaying over 1.5 seconds. In Darkin form, Blade's Reach <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'>knocks up enemies hit</span> for 1 second." }] },
		{ "name": "Kennen", "cc": [{ "key": "P", "name": "Mark of the Storm", "desc": "Kennen's abilities apply a stack of <i>Mark of the Storm</i> to enemies hit for 6 seconds, refreshing on subsequent applications and stacking up to 3 times. The third stack against a target consumes them all to <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>stun them</span> for 1.25 seconds." }] },
		{ "name": "Kha'Zix", "cc": [{ "key": "P", "name": "Unseen Threat", "desc": "After becoming unseen, Kha'Zix empowers his next basic attack against an enemy champion to deal bonus <span class='ap'>magic damage</span> and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slow them</span> by 25% for 2 seconds." }, { "key": "W", "name": "Evolved Spike Racks", "desc": "When evolved, Void Spike fires three clusters in a cone, <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slows</span> by 60% and reveals enemy champions hit for 2 seconds." }] },
		{ "name": "Kindred", "cc": [{ "key": "E", "name": "Mounting Dread", "desc": "Lamb fires a shot at the target enemy that <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slows them</span> by 50% for 1 second." }] },
		{ "name": "Kled", "cc": [{ "key": "Q", "name": "Bear Trap on a Rope" }, { "key": "R", "name": "CHAAAAAAAARGE!!!" }] },
		{ "name": "Kog'Maw", "cc": [{ "key": "E", "name": "Void Ooze" }] },
		{ "name": "K'Sante", "cc": [{ "key": "Q", "name": "Ntofo Strikes" }, { "key": "W", "name": "Path Maker" }, { "key": "R", "name": "All Out" }] },
		{ "name": "LeBlanc", "cc": [{ "key": "E", "name": "Ethereal Chains" }] },
		{ "name": "Lee Sin", "cc": [{ "key": "E", "name": "Cripple" }, { "key": "R", "name": "Dragon's Rage" }] },
		{ "name": "Leona", "cc": [{ "key": "Q", "name": "Shield of Daybreak" }, { "key": "E", "name": "Zenith Blade" }, { "key": "R", "name": "Solar Flare" }] },
		{ "name": "Lillia", "cc": [{ "key": "E", "name": "Swirlseed" }, { "key": "R", "name": "Lilting Lullaby" }] },
		{ "name": "Lissandra", "cc": [{ "key": "P", "name": "Iceborn Subjugation" }, { "key": "Q", "name": "Ice Shard" }, { "key": "W", "name": "Ring of Frost" }, { "key": "R", "name": "Frozen Tomb" }] },
		{ "name": "Lucian", "cc": [] },
		{ "name": "Lulu", "cc": [{ "key": "Q", "name": "Glitterlance" }, { "key": "W", "name": "Whimsy" }, { "key": "R", "name": "Wild Growth" }] },
		{ "name": "Lux", "cc": [{ "key": "Q", "name": "Light Binding" }, { "key": "E", "name": "Lucent Singularity" }] },
		{ "name": "Malphite", "cc": [{ "key": "Q", "name": "Seismic Shard" }, { "key": "R", "name": "Unstoppable Force" }] },
		{ "name": "Malzahar", "cc": [{ "key": "Q", "name": "Call of the Void" }, { "key": "R", "name": "Nether Grasp" }] },
		{ "name": "Maokai", "cc": [{ "key": "Q", "name": "Bramble Smash" }, { "key": "W", "name": "Twisted Advance" }, {"key": "E", "name": "Sapling Toss"}, { "key": "R", "name": "Nature's Grasp" }] },
		{ "name": "Master Yi", "cc": [] },
		{ "name": "Miss Fortune", "cc": [{ "key": "E", "name": "Make it Rain" }] },
		{ "name": "Mordekaiser", "cc": [{ "key": "E", "name": "Death's Grasp" }, { "key": "R", "name": "Realm of Death" }] },
		{ "name": "Morgana", "cc": [{ "key": "Q", "name": "Dark Binding" }, { "key": "R", "name": "Soul Shackles" }] },
		{ "name": "Nami", "cc": [{ "key": "Q", "name": "Aqua Prison" }, { "key": "E", "name": "Tidecaller's Blessing" }, { "key": "R", "name": "Tidal Wave" }] },
		{ "name": "Nasus", "cc": [{ "key": "W", "name": "Wither" }] },
		{ "name": "Nautilus", "cc": [{ "key": "P", "name": "Staggering Blow" }, { "key": "Q", "name": "Dredge Line" }, { "key": "E", "name": "Riptide" }, { "key": "R", "name": "Depth Charge" }] },
		{ "name": "Neeko", "cc": [{ "key": "E", "name": "Tangle-Barbs" }, { "key": "R", "name": "Pop Blossom" }] },
		{ "name": "Nidalee", "cc": [] },
		{ "name": "Nilah", "cc": [{ "key": "R", "name": "Apotheosis" }] },
		{ "name": "Nocturne", "cc": [{ "key": "E", "name": "Unspeakable Horror" }, { "key": "R", "name": "Paranoia" }] },
		{ "name": "Nunu & Willump", "cc": [{ "key": "W", "name": "Biggest Snowball Ever!" }, { "key": "E", "name": "Snowball Barrage" }, { "key": "R", "name": "Absolute Zero" }] },
		{ "name": "Olaf", "cc": [{ "key": "Q", "name": "Undertow" }] },
		{ "name": "Orianna", "cc": [{ "key": "W", "name": "Command: Dissonance" }, { "key": "R", "name": "Command: Shockwave" }] },
		{ "name": "Ornn", "cc": [{ "key": "Q", "name": "Volcanic Rupture" }, { "key": "E", "name": "Searing Charge" }, { "key": "R", "name": "Call of the Forge God" }] },
		{ "name": "Pantheon", "cc": [{ "key": "W", "name": "Shield Vault" }] },
		{ "name": "Poppy", "cc": [{ "key": "Q", "name": "Hammer Shock" }, { "key": "W", "name": "Steadfast Presence" }, { "key": "E", "name": "Heroic Charge" }, { "key": "R", "name": "Keeper's Verdict" }] },
		{ "name": "Pyke", "cc": [{ "key": "Q", "name": "Bone Skewer" }, { "key": "E", "name": "Phantom Undertow" }] },
		{ "name": "Qiyana", "cc": [{ "key": "R", "name": "Supreme Display of Talent" }] },
		{ "name": "Quinn", "cc": [{ "key": "E", "name": "Vault" }] },
		{ "name": "Rakan", "cc": [{ "key": "W", "name": "Grand Entrance" }, { "key": "R", "name": "The Quickness" }] },
		{ "name": "Rammus", "cc": [{ "key": "Q", "name": "Powerball" }, { "key": "E", "name": "Frenzying Taunt" }, { "key": "R", "name": "Soaring Slam" }] },
		{ "name": "Rek'Sai", "cc": [{ "key": "W", "name": "Un-Burrow" }] },
		{ "name": "Rell", "cc": [{ "key": "W", "name": "Ferromancy: Crash Down" }, { "key": "E", "name": "Attract and Repel" }, { "key": "R", "name": "Magnet Storm" }] },
		{ "name": "Renata Glasc", "cc": [{ "key": "Q", "name": "Handshake" }, { "key": "E", "name": "Loyalty Program" }, { "key": "R", "name": "Hostile Takeover" }] },
		{ "name": "Renekton", "cc": [{ "key": "W", "name": "Ruthless Predator" }] },
		{ "name": "Rengar", "cc": [{ "key": "E", "name": "Bola Strike" }] },
		{ "name": "Riven", "cc": [{ "key": "Q", "name": "Broken Wings" }, { "key": "W", "name": "Ki Burst" }] },
		{ "name": "Rumble", "cc": [{ "key": "E", "name": "Electro Harpoon" }, { "key": "R", "name": "The Equalizer" }] },
		{ "name": "Ryze", "cc": [{ "key": "W", "name": "Rune Prison" }] },
		{ "name": "Samira", "cc": [{ "key": "P", "name": "Daredevil Impulsive" }] },
		{ "name": "Sejuani", "cc": [{ "key": "Q", "name": "Arctic Assault" }, { "key": "W", "name": "Winter's Wrath" }, { "key": "E", "name": "Permafrost" }, { "key": "R", "name": "Glacial Prison" }] },
		{ "name": "Senna", "cc": [{ "key": "Q", "name": "Piercing Darkness" }, { "key": "W", "name": "Last Embrace" }] },
		{ "name": "Seraphine", "cc": [{ "key": "E", "name": "Beat Drop" }, { "key": "R", "name": "Encore" }] },
		{ "name": "Sett", "cc": [{ "key": "E", "name": "Facebreaker" }, { "key": "R", "name": "The Show Stopper" }] },
		{ "name": "Shaco", "cc": [{ "key": "W", "name": "Jack in the Box" }, { "key": "E", "name": "Two-Shiv Poison" }, { "key": "R", "name": "Hallucinate" }] },
		{ "name": "Shen", "cc": [{ "key": "Q", "name": "Twilight Assault" }, { "key": "E", "name": "Shadow Dash" }] },
		{ "name": "Shyvana", "cc": [{ "key": "R", "name": "Dragon's Descent" }] },
		{ "name": "Singed", "cc": [{ "key": "W", "name": "Mega Adhesive" }, { "key": "E", "name": "Fling" }] },
		{ "name": "Sion", "cc": [{ "key": "Q", "name": "Decimating Smash" }, { "key": "E", "name": "Roar of the Slayer" }, { "key": "R", "name": "Unstoppable Onslaught" }] },
		{ "name": "Sivir", "cc": [] },
		{ "name": "Skarner", "cc": [{ "key": "E", "name": "Fracture" }, { "key": "R", "name": "Impale" }] },
		{ "name": "Sona", "cc": [{ "key": "E", "name": "Song of Celerity" }, { "key": "R", "name": "Crescendo" }] },
		{ "name": "Soraka", "cc": [{ "key": "Q", "name": "Starcall" }, { "key": "E", "name": "Equinox" }] },
		{ "name": "Swain", "cc": [{ "key": "W", "name": "Vision of Empire" }, { "key": "E", "name": "Nevermove" }, { "key": "R", "name": "Demonic Ascension" }] },
		{ "name": "Sylas", "cc": [{ "key": "Q", "name": "Chain Lash" }, { "key": "E", "name": "Abduct" }] },
		{ "name": "Syndra", "cc": [{ "key": "W", "name": "Force of Will" }, { "key": "E", "name": "Scatter the Weak" }] },
		{ "name": "Tahm Kench", "cc": [{ "key": "Q", "name": "Tongue Lash" }, { "key": "W", "name": "Abyssal Dive" }, { "key": "R", "name": "Devour" }] },
		{ "name": "Taliyah", "cc": [{ "key": "Q", "name": "Threaded Volley" }, { "key": "W", "name": "Seismic Shove" }, { "key": "E", "name": "Unraveled Earth" }, { "key": "R", "name": "Weaver's Wall" }] },
		{ "name": "Talon", "cc": [{ "key": "W", "name": "Rake" }] },
		{ "name": "Taric", "cc": [{ "key": "E", "name": "Dazzle" }] },
		{ "name": "Teemo", "cc": [{ "key": "Q", "name": "Blinding Dart" }, { "key": "R", "name": "Noxious Trap" }] },
		{ "name": "Thresh", "cc": [{ "key": "Q", "name": "Death Sentence" }, { "key": "E", "name": "Flay" }, { "key": "R", "name": "The Box" }] },
		{ "name": "Tristana", "cc": [{ "key": "W", "name": "Rocket Jump" }, { "key": "R", "name": "Buster Shot" }] },
		{ "name": "Trundle", "cc": [{ "key": "Q", "name": "Chomp" }, { "key": "E", "name": "Pillar of Ice" }] },
		{ "name": "Tryndamere", "cc": [{ "key": "W", "name": "Mocking Shout" }] },
		{ "name": "Twisted Fate", "cc": [{ "key": "W", "name": "Pick A Card - Red and Gold" }] },
		{ "name": "Twitch", "cc": [{ "key": "W", "name": "Venom Cask" }] },
		{ "name": "Udyr", "cc": [{ "key": "E", "name": "Blazing Stampede" }, { "key": "R", "name": "Wingborne Storm" }] },
		{ "name": "Urgot", "cc": [{ "key": "Q", "name": "Corrosive Charge" }, { "key": "E", "name": "Disdain" }, { "key": "R", "name": "Fear Beyond Death" }] },
		{ "name": "Varus", "cc": [{ "key": "E", "name": "Hail of Arrows" }, { "key": "R", "name": "Chain of Corruption" }] },
		{ "name": "Vayne", "cc": [{ "key": "E", "name": "Condemn" }] },
		{ "name": "Veigar", "cc": [{ "key": "E", "name": "Event Horizon" }] },
		{ "name": "Vel'Koz", "cc": [{ "key": "Q", "name": "Plasma Fission" }, { "key": "E", "name": "Tectonic Disruption" }] },
		{ "name": "Vex", "cc": [{ "key": "P", "name": "Doom 'N Gloom" }, { "key": "E", "name": "Looming Darkness" }] },
		{ "name": "Vi", "cc": [{ "key": "Q", "name": "Vault Breaker" }, { "key": "R", "name": "Cease and Desist" }] },
		{ "name": "Viego", "cc": [{ "key": "W", "name": "Spectral Maw" }, { "key": "R", "name": "Heartbreaker" }] },
		{ "name": "Viktor", "cc": [{ "key": "W", "name": "Gravity Field" }] },
		{ "name": "Vladimir", "cc": [{ "key": "W", "name": "Sanguine Pool" }] },
		{ "name": "Volibear", "cc": [{ "key": "Q", "name": "Thundering Smash" }, { "key": "E", "name": "Sky Splitter" }, { "key": "R", "name": "Stormbringer" }] },
		{ "name": "Warwick", "cc": [{ "key": "E", "name": "Primal Howl" }, { "key": "R", "name": "Infinite Duress" }] },
		{ "name": "Wukong", "cc": [{ "key": "R", "name": "Cyclone" }] },
		{ "name": "Xayah", "cc": [{ "key": "E", "name": "Bladecaller" }] },
		{ "name": "Xerath", "cc": [{ "key": "W", "name": "Eye of Destruction" }, { "key": "E", "name": "Shocking Orb" }] },
		{ "name": "Xin Zhao", "cc": [{ "key": "Q", "name": "Three Talon Strike" }, { "key": "W", "name": "Wind Becomes Lightning" }, { "key": "E", "name": "Audacious Charge" }, { "key": "R", "name": "Crescent Guard" }] },
		{ "name": "Yasuo", "cc": [{ "key": "Q", "name": "Steel Tempest" }, { "key": "R", "name": "Last Breath" }] },
		{ "name": "Yone", "cc": [{ "key": "Q", "name": "Mortal Steel" }, { "key": "R", "name": "Fate Sealed" }] },
		{ "name": "Yorick", "cc": [{ "key": "W", "name": "Dark Procession" }, { "key": "E", "name": "Mourning Mist" }] },
		{ "name": "Yuumi", "cc": [{ "key": "Q", "name": "Prowling Projectile" }, { "key": "R", "name": "Final Chapter" }] },
		{ "name": "Zac", "cc": [{ "key": "Q", "name": "Stretching Strikes" }, { "key": "E", "name": "Elastic Slingshot" }, { "key": "R", "name": "Let's Bounce" }] },
		{ "name": "Zed", "cc": [] },
		{ "name": "Zeri", "cc": [{ "key": "W", "name": "Ultrashock Laser", "desc": "Zeri fires an electric pulse in the target direction that deals <span class='ap'>magic damage</span> to the first enemy hit and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slows them</span> for 2 seconds." }] },
		{ "name": "Ziggs", "cc": [{ "key": "W", "name": "Satchel Charge", "desc": "Actively, Ziggs hurls a charge to the target location, remaining there for 4 seconds and granting sight of the area. On recast, Ziggs detonates the charge, causing it to explode to deal <span class='ap'>magic damage</span> to nearby enemies and <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'>knock them back</span> away from the center of the explosion, though not through terrain." }, { "key": "E", "name": "Hexplosive Minefield", "desc": "Ziggs scatters a cluster of 11 proximity mines over the target location that grant sight of the area for 2 seconds, lasting for up to 10 seconds. Each mine within the area explodes upon contact with terrain or an enemy, dealing <span class='ap'>magic damage</span> and <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowing them</span> for 1.5 seconds." }] },
		{ "name": "Zilean", "cc": [{ "key": "Q", "name": "Time Bomb", "desc": "Zilean throws a ticking time bomb to the target location that grants sight of its surroundings. The bomb will attach itself to units that move within the epicenter, or those hit directly, revealing them. After 3 seconds, or when the attached unit dies, the bomb explodes to deal <span class='ap'>magic damage</span> to nearby enemies. The bomb detonates immediately if another bomb attaches itself to the same unit, <img src='/ext/icons/inlines/stun.png' class='inlineicon'> <span class='stun'>stunning nearby enemies</span> for a duration." }, { "key": "E", "name": "Time Warp", "desc": "If the target is an ally, they gain bonus movement speed. If the target is an enemy, they are <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slowed</span>." }] },
		{ "name": "Zoe", "cc": [{ "key": "W", "name": "Spell Thief", "desc": "Passively, whenever an enemy champion casts a summoner spell summoner spell or item active item active, they drop the corresponding Spell Shard. Enemy minions have a 10% chance to spawn with a random Spell Shard that drops and remains for 20 seconds if Zoe kills them. Actively, Zoe mimics the active of the collected Spell Shard." }, { "key": "E", "name": "Sleepy Trouble Bubble", "desc": "Zoe kicks a bubble in the target direction that bursts upon the first enemy hit, otherwise lingering at maximum range over 1 second, then becoming a trap for 5 seconds that bursts upon enemy contact. The burst deals <span class='ap'>magic damage</span> and inflicts <img src='/ext/icons/inlines/drowsy.png' class='inlineicon'> <span class='drowsy'>drowsy</span> for 1.4 seconds, which gradually <img src='/ext/icons/inlines/slow.png' class='inlineicon'> <span class='slow'>slows them</span> until they fall <img src='/ext/icons/inlines/sleep.png' class='inlineicon'> <span class='sleep'>asleep</span> for 2.25 seconds." }] },
		{ "name": "Zyra", "cc": [{ "key": "E", "name": "Grasping Roots", "desc": "Zyra shoots a surge of vines in the target direction that deals <span class='ap'>magic damage</span> to enemies hit and <img src='/ext/icons/inlines/root.png' class='inlineicon'> <span class='root'>roots them</span> for a duration." }, { "key": "R", "name": "Stranglethorns", "desc": "Zyra summons a monstrous thicket at the target location that deals <span class='ap'>magic damage</span> to enemies hit as it expands. After 2 seconds, the thicket snaps upward to <img src='/ext/icons/inlines/knockup.png' class='inlineicon'> <span class='knockup'>knock up enemies</span> within for 1 second." }] }
	]
};

export const cancels = {
	"champions": [
		{ "name": "Aatrox", "cc": [{"key": "Q", "name": "The Darkin Blade"}, { "key": "W", "name": "Infernal Chains" }] },
		{ "name": "Ahri", "cc": [{ "key": "E", "name": "Charm" }] },
		{ "name": "Alistar", "cc": [{ "key": "Q", "name": "Pulverize" }, { "key": "W", "name": "Headbutt" }, { "key": "E", "name": "Trample" }] },
		{ "name": "Amumu", "cc": [{ "key": "Q", "name": "Bandage Toss" }, { "key": "R", "name": "Curse of the Sad Mummy" }] },
		{ "name": "Anivia", "cc": [{ "key": "Q", "name": "Flash Frost" }, {"key": "W", "name": "Crystallize"}] },
		{ "name": "Annie", "cc": [{ "key": "P", "name": "Pyromania"}] },
		{ "name": "Aphelios", "cc": [{ "key": "Q", "name": "Gravitum - Active" }, { "key": "R", "name": "Moonlight Vigil" }] },
		{ "name": "Ashe", "cc": [{ "key": "R", "name": "Enchanted Crystal Arrow" }] },
		{ "name": "Aurelion Sol", "cc": [{ "key": "Q", "name": "Starsurge" }, { "key": "R", "name": "Voice of Light" }] },
		{ "name": "Azir", "cc": [{ "key": "R", "name": "Emperor's Divide" }] },
		{ "name": "Bard", "cc": [{ "key": "Q", "name": "Cosmic Binding" }, { "key": "R", "name": "Tempered Fate" }] },
		{ "name": "Bel'Veth", "cc": [{ "key": "W", "name": "Above and Below" }] },
		{ "name": "Blitzcrank", "cc": [{ "key": "Q", "name": "Rocket Grab" }, { "key": "E", "name": "Power Fist" }] },
		{ "name": "Brand", "cc": [{ "key": "Q", "name": "Sear" }] },
		{ "name": "Braum", "cc": [{ "key": "P", "name": "Concussive Blows" }, { "key": "R", "name": "Glacial Fissure" }] },
		{ "name": "Caitlyn", "cc": [{ "key": "W", "name": "Yordle Snap Trap" }] },
		{ "name": "Camille", "cc": [{ "key": "E", "name": "Hookshot" }, { "key": "R", "name": "The Hextech Ultimatum" }] },
		{ "name": "Cassiopeia", "cc": [{ "key": "W", "name": "Miasma" }, { "key": "R", "name": "Petrifying Gaze" }] },
		{ "name": "Cho'Gath", "cc": [{ "key": "Q", "name": "Rupture" }] },
		{ "name": "Corki", "cc": [{ "key": "W", "name": "Special Delivery" }] },
		{ "name": "Darius", "cc": [{ "key": "E", "name": "Apprehend" }] },
		{ "name": "Diana", "cc": [{ "key": "R", "name": "Moonfall" }] },
		{ "name": "Draven", "cc": [{ "key": "E", "name": "Stand Aside" }] },
		{ "name": "Ekko", "cc": [{ "key": "W", "name": "Parallel Convergence" }] },
		{ "name": "Elise", "cc": [{ "key": "E", "name": "Cocoon" }] },
		{ "name": "Evelynn", "cc": [{ "key": "W", "name": "Allure" }] },
		{ "name": "Fiddlesticks", "cc": [{ "key": "Q", "name": "Terrify" }] },
		{ "name": "Fiora", "cc": [{ "key": "W", "name": "Riposte" }] },
		{ "name": "Fizz", "cc": [{ "key": "R", "name": "Chum the Waters" }] },
		{ "name": "Galio", "cc": [{ "key": "W", "name": "Shield of Durand" }, { "key": "E", "name": "Justice Punch" }, { "key": "R", "name": "Hero's Entrance" }] },
		{ "name": "Gnar", "cc": [{ "key": "W", "name": "Wallop" }, { "key": "R", "name": "GNAR!" }] },
		{ "name": "Gragas", "cc": [{ "key": "E", "name": "Body Slam" }, { "key": "R", "name": "Explosive Cask" }] },
		{ "name": "Hecarim", "cc": [{ "key": "E", "name": "Devastating Charge" }, { "key": "R", "name": "Onslaught of Shadows" }] },
		{ "name": "Heimerdinger", "cc": [{ "key": "E", "name": "CH-2 Electron Storm Grenade" }] },
		{ "name": "Irelia", "cc": [{ "key": "E", "name": "Flawless Duet" }] },
		{ "name": "Ivern", "cc": [{ "key": "Q", "name": "Rootcaller" }, { "key": "R", "name": "Daisy!" }] },
		{ "name": "Janna", "cc": [{ "key": "Q", "name": "Howling Gale" }, { "key": "R", "name": "Monsoon" }] },
		{ "name": "Jarvan IV", "cc": [{ "key": "Q", "name": "Dragon Strike" }] },
		{ "name": "Jax", "cc": [{ "key": "E", "name": "Counter Strike" }] },
		{ "name": "Jayce", "cc": [{ "key": "E", "name": "Thundering Blow" }] },
		{ "name": "Jhin", "cc": [{ "key": "W", "name": "Deadly Flourish" }] },
		{ "name": "Jinx", "cc": [{ "key": "E", "name": "Flame Chompers!" }] },
		{ "name": "Kalista", "cc": [{ "key": "R", "name": "Fate's Call" }] },
		{ "name": "Karma", "cc": [{ "key": "E", "name": "Focused Resolve" }] },
		{ "name": "Kennen", "cc": [{ "key": "P", "name": "Mark of the Storm" }] },
		{ "name": "Kled", "cc": [{ "key": "Q", "name": "Bear Trap on a Rope" }, { "key": "R", "name": "CHAAAAAAAARGE!!!" }] },
		{ "name": "K'Sante", "cc": [{ "key": "Q", "name": "Ntofo Strikes" }, { "key": "W", "name": "Path Maker" }, { "key": "R", "name": "All Out" }] },
		{ "name": "LeBlanc", "cc": [{ "key": "E", "name": "Ethereal Chains" }] },
		{ "name": "Lee Sin", "cc": [{ "key": "R", "name": "Dragon's Rage" }] },
		{ "name": "Leona", "cc": [{ "key": "Q", "name": "Shield of Daybreak" }, { "key": "E", "name": "Zenith Blade" }, { "key": "R", "name": "Solar Flare" }] },
		{ "name": "Lillia", "cc": [{ "key": "R", "name": "Lilting Lullaby" }] },
		{ "name": "Lissandra", "cc": [{ "key": "W", "name": "Ring of Frost" }, { "key": "R", "name": "Frozen Tomb" }] },
		{ "name": "Lulu", "cc": [{ "key": "W", "name": "Whimsy" }, { "key": "R", "name": "Wild Growth" }] },
		{ "name": "Lux", "cc": [{ "key": "Q", "name": "Light Binding" }] },
		{ "name": "Malphite", "cc": [{ "key": "R", "name": "Unstoppable Force" }] },
		{ "name": "Malzahar", "cc": [{ "key": "R", "name": "Nether Grasp" }] },
		{ "name": "Maokai", "cc": [{ "key": "Q", "name": "Bramble Smash" }, { "key": "W", "name": "Twisted Advance" }, { "key": "R", "name": "Nature's Grasp" }] },
		{ "name": "Mordekaiser", "cc": [{ "key": "E", "name": "Death's Grasp" }] },
		{ "name": "Morgana", "cc": [{ "key": "Q", "name": "Dark Binding" }, { "key": "R", "name": "Soul Shackles" }] },
		{ "name": "Nami", "cc": [{ "key": "Q", "name": "Aqua Prison" }, { "key": "R", "name": "Tidal Wave" }] },
		{ "name": "Nautilus", "cc": [{ "key": "P", "name": "Staggering Blow" }, { "key": "Q", "name": "Dredge Line" }, { "key": "R", "name": "Depth Charge" }] },
		{ "name": "Neeko", "cc": [{ "key": "E", "name": "Tangle-Barbs" }, { "key": "R", "name": "Pop Blossom" }] },
		{ "name": "Nilah", "cc": [{ "key": "R", "name": "Apotheosis" }] },
		{ "name": "Nocturne", "cc": [{ "key": "E", "name": "Unspeakable Horror" }] },
		{ "name": "Nunu & Willump", "cc": [{ "key": "W", "name": "Biggest Snowball Ever!" }] },
		{ "name": "Orianna", "cc": [{ "key": "R", "name": "Command: Shockwave" }] },
		{ "name": "Ornn", "cc": [{ "key": "Q", "name": "Volcanic Rupture" }, { "key": "E", "name": "Searing Charge" }, { "key": "R", "name": "Call of the Forge God" }] },
		{ "name": "Pantheon", "cc": [{ "key": "W", "name": "Shield Vault" }] },
		{ "name": "Poppy", "cc": [{ "key": "W", "name": "Steadfast Presence" }, { "key": "E", "name": "Heroic Charge" }, { "key": "R", "name": "Keeper's Verdict" }] },
		{ "name": "Pyke", "cc": [{ "key": "Q", "name": "Bone Skewer" }, { "key": "E", "name": "Phantom Undertow" }] },
		{ "name": "Qiyana", "cc": [{ "key": "R", "name": "Supreme Display of Talent" }] },
		{ "name": "Quinn", "cc": [{ "key": "E", "name": "Vault" }] },
		{ "name": "Rakan", "cc": [{ "key": "W", "name": "Grand Entrance" }, { "key": "R", "name": "The Quickness" }] },
		{ "name": "Rammus", "cc": [{ "key": "Q", "name": "Powerball" }, { "key": "E", "name": "Frenzying Taunt" }, { "key": "R", "name": "Soaring Slam" }] },
		{ "name": "Rek'Sai", "cc": [{ "key": "W", "name": "Un-Burrow" }] },
		{ "name": "Rell", "cc": [{ "key": "W", "name": "Ferromancy: Crash Down" }, { "key": "E", "name": "Attract and Repel" }, { "key": "R", "name": "Magnet Storm" }] },
		{ "name": "Renata Glasc", "cc": [{ "key": "Q", "name": "Handshake" }, { "key": "R", "name": "Hostile Takeover" }] },
		{ "name": "Renekton", "cc": [{ "key": "W", "name": "Ruthless Predator" }] },
		{ "name": "Rengar", "cc": [{ "key": "E", "name": "Bola Strike" }] },
		{ "name": "Riven", "cc": [{ "key": "Q", "name": "Broken Wings" }, { "key": "W", "name": "Ki Burst" }] },
		{ "name": "Ryze", "cc": [{ "key": "W", "name": "Rune Prison" }] },
		{ "name": "Samira", "cc": [{ "key": "P", "name": "Daredevil Impulsive" }] },
		{ "name": "Sejuani", "cc": [{ "key": "Q", "name": "Arctic Assault" }, { "key": "E", "name": "Permafrost" }, { "key": "R", "name": "Glacial Prison" }] },
		{ "name": "Senna", "cc": [{ "key": "W", "name": "Last Embrace" }] },
		{ "name": "Seraphine", "cc": [{ "key": "E", "name": "Beat Drop" }, { "key": "R", "name": "Encore" }] },
		{ "name": "Sett", "cc": [{ "key": "E", "name": "Facebreaker" }, { "key": "R", "name": "The Show Stopper" }] },
		{ "name": "Shaco", "cc": [{ "key": "W", "name": "Jack in the Box" }, { "key": "R", "name": "Hallucinate" }] },
		{ "name": "Shen", "cc": [{ "key": "E", "name": "Shadow Dash" }] },
		{ "name": "Shyvana", "cc": [{ "key": "R", "name": "Dragon's Descent" }] },
		{ "name": "Singed", "cc": [{ "key": "W", "name": "Mega Adhesive" }, { "key": "E", "name": "Fling" }] },
		{ "name": "Sion", "cc": [{ "key": "Q", "name": "Decimating Smash" }, { "key": "R", "name": "Unstoppable Onslaught" }] },
		{ "name": "Skarner", "cc": [{ "key": "E", "name": "Fracture" }, { "key": "R", "name": "Impale" }] },
		{ "name": "Sona", "cc": [{ "key": "R", "name": "Crescendo" }] },
		{ "name": "Soraka", "cc": [{ "key": "E", "name": "Equinox" }] },
		{ "name": "Swain", "cc": [{ "key": "E", "name": "Nevermove" }] },
		{ "name": "Sylas", "cc": [{ "key": "E", "name": "Abduct" }] },
		{ "name": "Syndra", "cc": [{ "key": "E", "name": "Scatter the Weak" }] },
		{ "name": "Tahm Kench", "cc": [{ "key": "Q", "name": "Tongue Lash" }, { "key": "W", "name": "Abyssal Dive" }, { "key": "R", "name": "Devour" }] },
		{ "name": "Taliyah", "cc": [{ "key": "W", "name": "Seismic Shove" }, { "key": "E", "name": "Unraveled Earth" }, { "key": "R", "name": "Weaver's Wall" }] },
		{ "name": "Taric", "cc": [{ "key": "E", "name": "Dazzle" }] },
		{ "name": "Thresh", "cc": [{ "key": "Q", "name": "Death Sentence" }, { "key": "E", "name": "Flay" }] },
		{ "name": "Tristana", "cc": [{ "key": "R", "name": "Buster Shot" }] },
		{ "name": "Trundle", "cc": [{ "key": "E", "name": "Pillar of Ice" }] },
		{ "name": "Twisted Fate", "cc": [{ "key": "W", "name": "Pick A Card - Gold" }] },
		{ "name": "Udyr", "cc": [{ "key": "E", "name": "Blazing Stampede" }] },
		{ "name": "Urgot", "cc": [{ "key": "E", "name": "Disdain" }, { "key": "R", "name": "Fear Beyond Death" }] },
		{ "name": "Varus", "cc": [{ "key": "R", "name": "Chain of Corruption" }] },
		{ "name": "Vayne", "cc": [{ "key": "E", "name": "Condemn" }] },
		{ "name": "Veigar", "cc": [{ "key": "E", "name": "Event Horizon" }] },
		{ "name": "Vel'Koz", "cc": [{ "key": "E", "name": "Tectonic Disruption" }] },
		{ "name": "Vex", "cc": [{ "key": "P", "name": "Doom 'N Gloom" }] },
		{ "name": "Vi", "cc": [{ "key": "Q", "name": "Vault Breaker" }, { "key": "R", "name": "Cease and Desist" }] },
		{ "name": "Viego", "cc": [{ "key": "W", "name": "Spectral Maw" }] },
		{ "name": "Viktor", "cc": [{ "key": "W", "name": "Gravity Field" }] },
		{ "name": "Volibear", "cc": [{ "key": "Q", "name": "Thundering Smash" }] },
		{ "name": "Warwick", "cc": [{ "key": "E", "name": "Primal Howl" }, { "key": "R", "name": "Infinite Duress" }] },
		{ "name": "Wukong", "cc": [{ "key": "R", "name": "Cyclone" }] },
		{ "name": "Xayah", "cc": [{ "key": "E", "name": "Bladecaller" }] },
		{ "name": "Xerath", "cc": [{ "key": "E", "name": "Shocking Orb" }] },
		{ "name": "Xin Zhao", "cc": [{ "key": "Q", "name": "Three Talon Strike" }, { "key": "R", "name": "Crescent Guard" }] },
		{ "name": "Yasuo", "cc": [{ "key": "Q", "name": "Steel Tempest" }, { "key": "R", "name": "Last Breath" }] },
		{ "name": "Yone", "cc": [{ "key": "Q", "name": "Mortal Steel" }, { "key": "R", "name": "Fate Sealed" }] },
		{ "name": "Yorick", "cc": [{ "key": "W", "name": "Dark Procession" }] },
		{ "name": "Yuumi", "cc": [{ "key": "R", "name": "Final Chapter" }] },
		{ "name": "Zac", "cc": [{ "key": "Q", "name": "Stretching Strikes" }, { "key": "E", "name": "Elastic Slingshot" }, { "key": "R", "name": "Let's Bounce" }] },
		{ "name": "Ziggs", "cc": [{ "key": "W", "name": "Satchel Charge" }] },
		{ "name": "Zilean", "cc": [{ "key": "Q", "name": "Time Bomb" }] },
		{ "name": "Zoe", "cc": [{ "key": "W", "name": "Spell Thief" }, { "key": "E", "name": "Sleepy Trouble Bubble" }] },
		{ "name": "Zyra", "cc": [{ "key": "E", "name": "Grasping Roots" }, { "key": "R", "name": "Stranglethorns" }] }
	]
}